### ISSUE TITLE
Static condensation in Member3D.py

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#10]
**Member3D.py**

1. Static condensation

I don't unterstand because static condensation is used ( for example to built stiffness matrix, local fixed end reaction vector) and how it works. 

2. Member local fixed end reaction vector

Why __fer_Unc() is used in this part of code?
![Cattura](https://user-images.githubusercontent.com/56585383/67852600-fd569500-fb0c-11e9-8481-9b7fe8fa418e.JPG)

**FEModel3D.py**

Why fer() is used to assemble the global fixed end reacton vector? In Member3D.py, fer( ) is referred in local refering system. I should use FER () defined in Member3D.py, which is obtained after rotation by means T matrix

![Cattura](https://user-images.githubusercontent.com/56585383/67852720-3bec4f80-fb0d-11e9-9949-5c9f6a9a5b60.JPG)

**Comment by JWock82** [comment]
Static condensation is used to account for member end releases. We start with the typical member stiffness matrix and fixed end reaction vector, and then we condense out any "released" degrees of freedom the use has specified.

You don't need to be concerned with any of these matrices unless you want to verify them for yourself. I've built simple wrappers around the object model to keep the user's interaction with matrices to a minimum. For example, the "FEModel3D.DefineReleases()" method will tell PyNite to take care of condensing the matrices so you don't have to deal with it.

fer() is the member's local fixed end reaction vector. If no end releases have been defined, fer() and __fer_Unc() return the same vector.
