### ISSUE TITLE
running pynite without scipy

### ISSUE THREAD

**Issue by psychomiller** [JWock82/PyNite#107]
Dear Craig and hello everyone,

as described in FEModel3D, scipy is used to make pynite work faster with a huge amount of nodes.
It would be great, if there is a possibility to use pynite without scipy also.
Pynite allows to pass `sparse=False` as argument to the function `analyze` in FEModel3D:

`truss.analyze(check_statics=False, sparse=False)`

Anyway: Scipy is still imported in FEModel3D.py
Furthermore coo_matrix and lil_matrix is is called in the code afterwards.
Would it be possible to make conditionals in order to avoid to load and to use scipy?
(I would like to make a simple add-on for pynite in blender 3D. When running blender 3D on linux, it is possible to use pip in order to install additional modules to blender python. When switching to other operating systems, this would be a limitation. But maybe someone has also another idea how to make this work.)

Thanks for your answers in advance!

Greetings,
Chris

**Comment by bewegende-Architektur** [comment]
Hey there,

there is already a first version of Phänotyp, an Add-On for Blender3D, that is making FEA available in blender and more: https://github.com/bewegende-Architektur/Phaenotyp There are some tutorials on youtube. You can find the link in the repository.

Sorry for coming back to this topic, but is there a simple possibility to avoid scipy to be used by pynite? This would be great in order to avoid the installation progress via pip on users computers.

Greetings,
Chris

**Comment by JWock82** [comment]
I’ve got a solution working that doesn’t use scipy for dense solutions. I’m going to test it a little more and then push it out.

The way you’ve quoted PyNite is fine.

**Comment by bewegende-Architektur** [comment]
Awesome! Thank you very much for your time! Hope you have great holidays 😃

Greetings,
Chris

**Comment by JWock82** [comment]
This issue has been addressed in version 0.0.53. You'll need to set `sparse=False` when you use the `analyze` method, or the `analyze_PDelta` method. Let me know if you notice any issues with it. All unit tests for the code passed so I don't believe there are any.

**Comment by JWock82** [comment]
Do you mind if I list Phänotyp on PyNite's wiki as an example project?

**Comment by psychomiller** [comment]
Dear Craig,

Amazing! Thank you very much for your time. I will make an update.

Of course! Feel free to but it in on the Wiki :)

Greetings,
Chris

Dr. Christoph Müller
+43 (0) 650 340 53 16 
www.bewegende-Architektur.com

**Comment by bewegende-Architektur** [comment]
Dear Craig,

Amazing! Thank you very much for your time. I will make an update.

Of course! Feel free to but it in on the Wiki :)

Greetings,
Chris
