### ISSUE TITLE
Cannot Import PyNite

### ISSUE THREAD

**Issue by Corentin1985** [JWock82/PyNite#111]
Hi,

I just installed PyNite with pip.

Installation ended correctly.

But when I want to use it, if I type "import pynite", I get "No module named 'PyNite'".

Other imports such as "import numpy" or whatever work just fine.

I work with WinPython-64-bit-3.6.0.1.Qt5.

**Comment by JWock82** [comment]
Did you use `pip install PyNite` instead of `pip install PyNiteFEA`? There is another module out there called `pynite` so I had to add `FEA` to the end of the PyPi package. If you love playing the video game Fortnite then maybe `pynite` is what you want though.

**Comment by Corentin1985** [comment]
Thanks for the quick reply.
I tried both. None worked.
So I tried with a more recent Python and it still does not work, I really don't get it.

**Comment by JWock82** [comment]
Try `from PyNite import FEModel3D`.

**Comment by Corentin1985** [comment]
Just tried it. Same error. Really confusing.

**Comment by JWock82** [comment]
Do you have multiple versions of Python installed?

**Comment by JWock82** [comment]
My guess is that `pip` did not install `PyNite` to a location on your active interpreter's `PYTHONPATH``.

**Comment by Corentin1985** [comment]
I do indeed have multiple versions installed.
I'll check the pythonpath, not sure how though.
And what about the discussion I submitted about thermal loads?
Best regards.

**Comment by JWock82** [comment]
Did you ever figure this issue out? I'd like to close it out.

**Comment by Corentin1985** [comment]
Sorry, I never managed to get this work, but I guess that's just me. You can close. Best regards.

**Comment by Karltlbm** [comment]
Hi ! 
I have the same issue, i installed PyNiteFEA with pip succesfully (it is rightly in my pip list).
I am using a conda env.

The error is :

```
from PyNite import FEModel3D

ModuleNotFoundError: No module named 'PyNite'
```

Any news on this ?
