### ISSUE TITLE
Mesh functions cannot be used repeatedly

### ISSUE THREAD

**Issue by ickby** [JWock82/PyNite#115]
Creating two different RectangularMeshes does lead to wrong mesh sizes if no control values are provided.

    from PyNite.Mesh import RectangleMesh
    first = RectangleMesh(1, 2, 2, 1, 1)
    second = RectangleMesh(1, 1, 1, 1, 1)
    first.generate()
    second.generate()
    
    second.last_node.X # will be 2 instead of 1
    second.last_node.Y # will be 2 instead of 1

The Problem is using mutable lists as default arguments for y_control and x_control. See https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/

**Comment by JWock82** [comment]
I'll adjust this. Thanks for the guidance.

**Comment by JWock82** [comment]
I just addressed this in the latest commit. It will be released with the next version.
