### ISSUE TITLE
Nodal spring direction sign

### ISSUE THREAD

**Issue by roger1017** [JWock82/PyNite#118]
Hi Craig,

Thanks for the amazing work.

I noticed that if I don't specify spring direction (assuming spring can take both tension and compression), below code will give an error.

![image](https://user-images.githubusercontent.com/52928495/157197153-fe4b83f5-e937-427f-bb32-10906d162de7.png)

**Comment by JWock82** [comment]
Thanks for reporting. Reports like this from users go a long way to making PyNite more robust. I'll try to get to this this weekend sometime.

**Comment by JWock82** [comment]
I just fixed this in the GitHub repository. It will be included in the next PyPI release.
