### ISSUE TITLE
Modify fucntions

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#12]
I need to modify some fucntions within classes in order to test the program with different examples. I have tried to modify a generic function but I don't see any changing when code is running. How is possible? Do i have to do uninstall and install again?

**Comment by JWock82** [comment]
I'm not sure what function you've changed or how you've changed it. I'm not sure why you'd need to modify the program to test it. Most of the important methods and attributes that create the underlying stiffness and load matrices are public members that can be readily accessed. For example, type `help(FEModel3D)` into a Python terminal after importing `FEModel3D` and you can see all the class members available to you.

When I run example problems, I create a separate .py file for each example. You can see some of the examples I've tested against in the "Testing & Debugging" folder on GitHub.

Regardless, I definitely recommend upgrading to the latest version using `$ pip install --upgrade PyNiteFEA` from the command line. I made some important changes last week that fixed some major bugs in the global transformation matrix.

**Comment by LcnGnd** [comment]
For example, i want to try modify discretization used to plot shear, moment etc. Also, I'd like add new type load like thermal variation (constant and linear) and concentreated torsional moment. In order to do this developing, I have to follow some particular procedure or modify methods and attributes in python files in my pc (FEModel3D.py, Member3D.py, etc...) is enough?

**Comment by JWock82** [comment]
For what you'd like to do I'd recommend cloning PyNite to your local PYTHONPATH directory. You should probably uninstall PyNite using pip before cloning so there's no ambiguity between the two versions.

Those are great ideas for features to add to PyNite, but I've got other priorities I'd like to take care of first. Once you've cloned it I'd recommend starting a new branch for your code. When you get it working I believe you can issue a pull request for the branch and I can review the code and then merge it with PyNite.

**Comment by LcnGnd** [comment]
Sorry, how does work PYTHONPATH? I've tried to modify methods and attributes in python files in my pc (FEModel3D.py, Member3D.py, etc...) but i don't see any changing.

**Comment by JWock82** [comment]
PYTHONPATH is a system environment variable that tells python which folders to look in when using an import statement. You can edit environment variables such as PYTHONPATH in Windows 10 by searching "Environment Variables" in the start menu search bar.
