### ISSUE TITLE
Model Re-Analysis

### ISSUE THREAD

**Issue by bjhowie** [JWock82/PyNite#133]
Hi, this is not so much a bug as maybe an unexpected behavior. I'm trying to model a continuous concrete beam and need to update the stiffness of the individual member elements following an initial analysis to determine the relevent service moment to calculate the cracked stiffness of the beam.

I'm trying to achieve this by updating the Iy property of the members then re-running the analysis. Only problem is the results dont seem to update. What am i doing wrong.

**Comment by JWock82** [comment]
Iy is for weak axis bending. Iz is for strong axis bending.

Thanks,

Craig Brinck
________________________________
From: bjhowie ***@***.***>
Sent: Monday, October 31, 2022 5:26 AM
To: JWock82/PyNite ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JWock82/PyNite] Model Re-Analysis (Issue #133)


Hi, this is not so much a bug as maybe an unexpected behavior. I'm trying to model a continuous concrete beam and need to update the stiffness of the individual member elements following an initial analysis to determine the relevent service moment to calculate the cracked stiffness of the beam.

I'm trying to achieve this by updating the Iy property of the members then re-running the analysis. Only problem is the results dont seem to update. What am i doing wrong.

**Comment by bjhowie** [comment]
I've tried changing Iy, Iz and E. No change.

There's no stiffness matrix buffer or results set that i need to manually clear before re-running?

**Comment by JWock82** [comment]
I'll have a closer look at this when I get a moment - it may be a bug. You should be able to swap out "I" values and rerun. It's been a while, but I believe I set up the stiffness matrix to re-assemble anytime you invoke the analyze command.

**Comment by JWock82** [comment]
I've experimented with it and it seams to be working for me. Here's a simple working example:

        from PyNite import FEModel3D

        beam = FEModel3D()

        # Define the nodes
        beam.add_node('N1', 0, 0, 0)
        beam.add_node('N2', 10*12, 0, 0)
        beam.add_node('N3', 20*12, 0, 0)

        # Define the supports
        beam.def_support('N1', True, True, True, True, False, False)
        beam.def_support('N2', True, True, True, False, False, False)
        beam.def_support('N3', True, True, True, False, False, False)

        # Create members (all members will have the same properties in this example)
        Iz = 24*30**2/12
        Iy = 30*24**3/12
        J = Iz + Iy
        E = 57*(4500)**0.5
        G = 0.4*E
        A = 24*30
        
        beam.add_member('M1', 'N1', 'N3', E, G, Iy, Iz, J, A)

        # Add a member load
        w = 0.100*(10*12)
        beam.add_member_dist_load('M1', 'FY', w, w)

        # Analyze the model
        beam.analyze()

        d1 = beam.Members['M1'].min_deflection('dy')

        # Change the moment of inertia to account for cracking
        Iz = 0.35*Iz
        beam.Members['M1'].Iz = Iz

        beam.analyze()

        d2 = beam.Members['M1'].min_deflection('dy')

        print(d1, d2)

**Comment by bjhowie** [comment]
So as it turns out, I was using an older version. I upgraded and it all works fine now. 

Sorry about that. Probbaly the first thing i should have done!
