### ISSUE TITLE
Enforced Nodal Displacements are Overridden by Spring Supports

### ISSUE THREAD

**Issue by JWock82** [JWock82/PyNite#134]

**Comment by JWock82** [comment]
Yes and yes. It's the next thing I plan to work on. I opened this issue a few days ago to notify the users of the bug. I don't like bugs like this one to live for long.

**Comment by JWock82** [comment]
Instead of `AddNodeDisplacement`, try `def_node_disp`. I refactored the code a while back and renamed some of the methods. My unit tests for support settlement problems are not showing any errors. I'm thinking it works fine. Let me know if this fixes it for you.

**Comment by JWock82** [comment]
I just renamed this issue after figuring out what the real problem is. Enforced displacements are overridden by spring supports and are ignored.

**Comment by JWock82** [comment]
This issue has been resolved.

**Comment by janetunde** [comment]
Thank you very much!!
