### ISSUE TITLE
Simple beam with distributed axial load

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#14]
I've analyzed a simple beam with a constant distributed axial load and with hinges at both nodes. I expected to obtained a linear and symmetric axial stress. This is correct because both nodes are able to react in terms of axial load.
 

#Units N e m

###Import `FEModel3D` from `PyNite`
from PyNite import FEModel3D
from PyNite import Visualization

###Create a new finite element model
Beam = FEModel3D()
L=5 #m

###Nodes 
Beam.AddNode("N1", 0, 0, 0)
Beam.AddNode("N2", L, 0, 0)

###Beams (30x50 cm)
E=2.1e11 #N/m^2
G=1
Iy=0.001125 #m^4
Iz=0.003125 #m^4
J=1
A=0.15 #m^2

Beam.AddMember("M1", "N1", "N2",E,G,Iy,Iz,J,A)

###Supports
Beam.DefineSupport("N1",True, True, True, True, True, True) 
Beam.DefineSupport("N2",True, True, True, False, True, True)
view=Visualization.RenderModel(Beam,0.5)

###Load 
Beam.AddMemberDistLoad("M1","Fx",10,10,0,5)
#Analyze
Beam.Analyze()
#Diagrams V,M and displacements
Beam.GetMember("M1").PlotAxial()
#Reactions
print("R1=",Beam.GetNode("N1").RxnFX,"N")
print("R2=",Beam.GetNode("N2").RxnFX,"N")

Results obtained are different from thinked ones. Axial diagram starts from 0 and finish to the value of total axial load applicated to the beam. Alse both reactions are zero. 

![Cattura](https://user-images.githubusercontent.com/56585383/69913872-c510e200-143d-11ea-99ad-bba9af9d7cbc.JPG)

How is possible? Is there any problem in my code? Or is there any problem in PyNite code? 
Thanks

**Comment by JWock82** [comment]
This appears to be a bug. I'll make this my next priority.

**Comment by LcnGnd** [comment]
Ok, thanks. I'll wait and then try again!

**Comment by JWock82** [comment]
I think I've got it fixed now. I'll update the pip distribution soon, but for now if you pull the latest changes to your clone it should update.

**Comment by JWock82** [comment]
I've updated the pip version of PyNite on PyPI.

**Comment by LcnGnd** [comment]
Now it works. Thanks!
