### ISSUE TITLE
Beam's local referring system

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#15]
I'm using PyNiteFEA for my master's degree thesis. Using PyNiteFEA I think that a way to oriented y and z local axis si needed. I have to control how local system is oriented becasue in a complicated 3D model could be difficult understand all local referring systems that are  defined by PyNite.
My idea is to use auxiliar points. It is possible to implement in PyNiteFEA?

**Comment by JWock82** [comment]
Have a look at the code in Member3D.py for the member's transformation matrix, T. You'd have to reformulate the transformation matrix to account for a rotation about the member's local x-axis. In other words, the local z-axis direction cosines would need to change. You could then use the cross-product of the local z-axis with the local x-axis to derive the local y-axis.

Please use PyNite with caution. It's still a very young project. It still has a lot of limitations/assumptions built into it, and as you've seen, I'm still finding bugs here and there.
