### ISSUE TITLE
Post-processing - analysis fails for two span beams 

### ISSUE THREAD

**Issue by Zardasht84** [JWock82/PyNite#157]
**Describe the bug**
Recently I found your library as a good source to perform an elastic-static analysis. I use Excel-sheet as GUI and your library to do the static parts. I calculate from one span to multiple spans with different section properties. During review your code I found a bug when 
there is a one or two spans with pinned support in the beginning and roller support at intermediate support and at the end. The code raise "MatrixRankWarning: Matrix is exactly singular"
If you change the support condition at the end from roller to clamped, then the scripts work as it should!

There is a bug in the code!

I screenshot the code and to explain the problem.

A requirement: getting x-segment of member length and corresponding moment, shear and deformation as a list. 
Instead of making a list or array then run in the for-loop with every x-value to get the result. 

The code:
![image](https://github.com/JWock82/PyNite/assets/134142633/77e488d8-e963-4687-ba75-b268cb4c617b)

Error:
![image](https://github.com/JWock82/PyNite/assets/134142633/e7f62cc2-ae29-48e1-bc6e-d3c3eb5c1582)

**Comment by JWock82** [comment]
Your model is unstable. There's nothing preventing the beam from spinning about the global X-axis.

**Comment by Zardasht84** [comment]
This is correct. I found out to prevented the beam from rotation about X-axis with code 
Pinned support = (True, True, True, True, False, False).  Then it works as it should :)
