### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#16]
I've introduced in PyNiteFEA the possibilty to orient local referring system by means auxiliary nodes. Formulation on transformation matrix is changed too.  Also I've introduced in Visualization.py another function in order to view the deformed configuration of the model using the deformed nodes coordinates connected by straight line. Now I m working to view the real deflection of every elements. 
How can I added these changes to the online code?

**Comment by JWock82** [comment]
Issue a pull request for the changes, and then I can review them, comment on them, and merge them with the main branch. Depending on how big the pull request is it may take some time for me to review it and merge it.

**Comment by LcnGnd** [comment]
Can you help me for sending pull request? I've some problems with the site, I don't understand what i have to insert of my code.

**Comment by JWock82** [comment]
I'm not a GitHub expert either, but I think you can do this by making the changes in the fork you created. Commit the changes to your fork, and then from your fork you can issue a pull request that they be merged with the master branch of my repository. That will give me the chance to review your code and accept/decline/comment on it.

I would suggest updating your fork first to make sure github doesn't find any issues/inconsistencies. You should be able to do this by pulling my latest code into your fork.

**Comment by JWock82** [comment]
For more info check this link: [https://zellwk.com/blog/submit-pull-request/](url)
