### ISSUE TITLE
Error Creating Members with Aux Nodes

### ISSUE THREAD

**Issue by bjhowie** [JWock82/PyNite#162]
There is a typo in the code when creating members with auxilliary nodes defined.
In the FEModel3D class, the keyword argument passed to the Physical member constructor is 'auxnode', whereas the Physical member '__init__' method expects the keyword argumne to be 'aux_node'.

I'd submit a pull request, but I'm not sure i know how to, sorry.

**Comment by JWock82** [comment]
Thanks for reporting this. I don't use that feature myself, so it seems to have slipped through the cracks. Looks like a simple fix.

I really need to just get the program away from aux nodes and allow the user to specify a rotation angle.

**Comment by JWock82** [comment]
Pull requests are pretty easy. If you create a fork of the repository you can change the code there and then issue a pull request from your fork on Github. I think you'll get a "Pull Shark" badge on your Github profile the first time one of your pull requests is merged. If you don't want to do the pull request I can do it.

**Comment by bjhowie** [comment]
Yeah OK. I'll give it a try. Got to learn how to do it some day.

I quite like the aux node method of specifying member local axes as it is independent of the topology of the member. A rotation angle would differ in a member running from node 'A' to node 'B' than in one running from node 'B' to node 'A'.

**Comment by JWock82** [comment]
The pull request has been merged.
