### ISSUE TITLE
Rotational Symmetry

### ISSUE THREAD

**Issue by PetterTh** [JWock82/PyNite#174]
Hi

Thank you for making pyNite.

Is it possible to simulate rotational symmetry/periodicity with the pyNite?

**Comment by JWock82** [comment]
Is this related to axisymmetric problems? No.

**Comment by PetterTh** [comment]
Hi 
No, not a 2D axisymmetry problem. 
Think a turbine-impeller with n equal blades and only simulating 1/n parts of the impeller.
Connecting the "left" and "right" parts trough a rotational periodicity connection.
![b9be50a7-5c40-4762-97fd-a9970052fd4c_impeller](https://github.com/JWock82/PyNite/assets/1391075/33210611-ecde-414b-b9cd-69f3f6dc5b75)

**Comment by JWock82** [comment]
I'm unfamiliar with this type of connection. My expertise is primarily in building/civil type structures, rather than mechanical components. Pynite is built around those types of problems, though it could be extended to do other types.
