### ISSUE TITLE
'Quad3D' object has no attribute 'LoadCombos'

### ISSUE THREAD

**Issue by angelmusonda** [JWock82/PyNite#176]
https://github.com/JWock82/PyNite/blob/a22b0272361f2a995bbaff4db637fd928d3286d3/PyNite/Mesh.py#L139C15-L139C15

I suppose the above line was supposed to be:  _for load_combo in **model**.LoadCombos.values()_ as opposed to _for load_combo in **element**.LoadCombos.values()_?

This applies to the other methods as well for accessing the min and max values in a mesh.

**Comment by JWock82** [comment]
This looks like a bug that was introduced when I moved the analysis code into its own module. I think I know how to fix this. Thanks for reporting it. I’ll get this corrected shortly.

**Comment by JWock82** [comment]
This has been fixed in version 0.0.82.
