### ISSUE TITLE
PyNite Import Issue

### ISSUE THREAD

**Issue by tovarog23** [JWock82/PyNite#181]
ModuleNotFoundError takes place when trying to import PyNite into a project. 
The package has been installed correctly yet this error still takes place. 

Seems like it can be corrected if all import statements are changed within the package using "pynite" instead of "PyNite".

**Comment by JWock82** [comment]
Sounds like you installed PyNite instead of PyNiteFEA. They are not the same.

**Comment by JWock82** [comment]
Did you get this issue resolved? I'd like to close this issue out.

**Comment by tovarog23** [comment]
Problem resolved, the issue was not with PyNite but with another module I imported that uses this package.

**Comment by Karltlbm** [comment]
Hi ! I am having the same issue, can you give some details about how you solved this please ?
