### ISSUE TITLE
Issue initalising PhysMember

### ISSUE THREAD

**Issue by linokl** [JWock82/PyNite#183]
Hi Craig

**I think there is a bug due to a mismatch in variable positions in the initialisation call for PhysMember**

In PhysMember, when you initialise the member the super init is called with "model" variable in 10th position

<img width="960" alt="image" src="https://github.com/JWock82/PyNite/assets/20646443/37580773-ad51-4f55-80e5-ede5cfc6c446">

In Member3D, in the initialisation function, "model" variable is in 6th position

<img width="914" alt="image" src="https://github.com/JWock82/PyNite/assets/20646443/af173213-b075-439c-8f12-bdad16351a09">

When I am initialising the PhysMember i get an error after updating the pynite to the latest version. Possibly due to this issue I think 

Regards
Lino

**Comment by JWock82** [comment]
That's strange. All my unit tests are passing. I'll look into this a bit closer. I just changed it, and all my unit tests failed.

**Comment by linokl** [comment]
thank you
