### ISSUE TITLE
Variable cross-section along member

### ISSUE THREAD

**Issue by polyakszabolcs92** [JWock82/PyNite#184]
It would be a nice addition if the user could define beam (bar members) with **variable cross sections (or heights) at the start and endpoints**.
Right now you have to work around it by manually dividing such a member to smaller elements with an interpolated cross-section.
It is a commmon member type in steel and reinforced concrete design.

**Comment by JWock82** [comment]
I don't have any plans to add this feature myself. I don't have a lot of use for it personally. I would be willing to accept a pull-request for this feature if it was implemented well.
