### ISSUE TITLE
Issue initalising PhysMember second issue with variable position

### ISSUE THREAD

**Issue by linokl** [JWock82/PyNite#186]
Hi Craig,

Me again, sorry I found another similar error after your last fix on PhysMember initialisation issue when trying to use the updated module.

I think there is a bug due to a mismatch in variable positions in the initialization call for PhysMember

In PhysMember, when you initialize the member the super init is called with "model" after the area (A) variable
<img width="959" alt="image" src="https://github.com/JWock82/PyNite/assets/20646443/a03207ed-df1a-45b4-abcc-3aaa7771110d">

In Member3D, in the initialization function, "model" variable after "material"
<img width="694" alt="image" src="https://github.com/JWock82/PyNite/assets/20646443/3cc62132-8d6d-4a9e-8092-e92f12fd6d09">

This is causing issue initalising PhysMember

Regards
Lino

**Comment by JWock82** [comment]
I just fixed this. Look for the fix in v0.0.93. Thanks for reporting!
