### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#19]
Thanks for considering my new features. Now i wait to download new PyNite version by means pip.
Also, I have another question: what is module **__init__.py** used for?

**Comment by JWock82** [comment]
Thanks for your help with this feature. I'll get it pushed to pip soon.

__init__.py is a file that tells the Python interpreter that all the files in the PyNite folder are part of a package. It signals to Python that these files are all part of the same program. Without __init__.py Python will view each of these files as separate python programs. It can also be used to automatically import libraries when the user imports PyNite.

See below for more info on __init__.py:
https://stackoverflow.com/questions/448271/what-is-init-py-for

**Comment by JWock82** [comment]
PyPi is now updated. You should be able to get version 0.0.6 using pip.
