### ISSUE TITLE
Inactive tension_only member still takes load

### ISSUE THREAD

**Issue by lddllddl** [JWock82/Pynite#210]
**Describe the bug**

Inactive tension_only member still takes load

**To Reproduce**

See this self-contained example.
Cantilever stayed with cable
All members are two-force

In the amended case, an additional cable stay is added to the opposite side, which is supposed to have no effect.

```pythonfrom PyNite import FEModel3D

# Create a new finite element model
braced_frame = FEModel3D()
braced_frame.add_node('N1', 0, 0, 0)
braced_frame.add_node('N2', 100, 0, 0)
braced_frame.add_node('N3', 0, 10, 0)

E = 29000 # ksi
G = 11400 # ksi
nu = 0.3  # Poisson's ratio
rho = 0.490/12**2  # Density (kci)
braced_frame.add_material('Steel', E, G, nu, rho)

Iy = 3 # in^4
Iz = 3 # in^4
J = 0.0438 # in^4
A = 1.94 # in^2

braced_frame.add_member('push', 'N1', 'N2', 'Steel', Iy, Iz, J, A)
braced_frame.add_member('pullup', 'N3', 'N2', 'Steel', Iy, Iz, J, A, tension_only=True)
braced_frame.def_releases('pullup', Ryi=True, Rzi=True, Ryj=True, Rzj=True)
braced_frame.def_releases('push', Ryi=True, Rzi=True, Ryj=True, Rzj=True)


braced_frame.def_support('N2', *[False]*2, *[True]*4)
braced_frame.def_support('N1', *[True]*6)
braced_frame.def_support('N3', *[True]*6)
braced_frame.add_node_load('N2', 'FY', -10)

braced_frame.analyze()
print('pullup', braced_frame.Members['pullup'].max_axial())
print('push',braced_frame.Members['push'].max_axial())
print('==========================')


braced_frame.add_node('N4', 0, -10, 0)
braced_frame.add_member('pulldown', 'N4', 'N2', 'Steel', Iy, Iz, J, A, tension_only=True)
braced_frame.def_releases('pulldown', Ryi=True, Rzi=True, Ryj=True, Rzj=True)
braced_frame.def_support('N4', *[True]*6)

braced_frame.analyze()
print('pullup',braced_frame.Members['pullup'].max_axial())
print('push',braced_frame.Members['push'].max_axial())

print('pulldown',braced_frame.Members['pulldown'].max_axial())
print('pulldown',braced_frame.Members['pulldown'].active)

``` 
Output (both latest main as well latest pypi release)

```
pullup -100.49875621120889
push 99.99999999999997
==========================
pullup -50.24937810560445
push 99.99999999999997
pulldown 50.24937810560445
pulldown {'Combo 1': False}
```

Obviously the lower "pulldown" cable is (incorrectly) sharing the load as a compressive member, even though it is (correctly) marked as inactive, halving the load the "pullup" cable takes.

**Expected behavior**
The force in "pullup" cable in the amended should remain the same.

**Comment by lddllddl** [comment]
Thanks for the reply - the problem is not really the inactive member though, because it is trivial to check if it is active first (though some doc may help). 

Note that the other cable (N3-N2) (always active) gets its load halved, as if the slack cable (N4-N2) takes away half the load by acting as a compression member. It is the load on the active cable that is a problem.

**Comment by JWock82** [comment]
I've reviewed the code and this is definitely a bug. This shouldn't be too hard to isolate and resolve. I'll make this my top priority for Pynite.

**Comment by JWock82** [comment]
I'm closing in on this issue. It appears the global nodal displacements are correct, and the stiffness matrix is correct, but the member internal forces are still storing results from the prior iteration before the T/C member deactivates. I should have this resolved soon.

**Comment by lddllddl** [comment]
Thanks. Yes I think the displacements are correct (being identical in both cases) as well - I should have checked that earlier!

**Comment by JWock82** [comment]
This issue has been resolved in the latest release. It was a bug. I will flag this issue as a bug for documentation.
