### ISSUE TITLE
Itemset - compatibility issue with APIs in Numpy 2.1.

### ISSUE THREAD

**Issue by thisisapple** [JWock82/Pynite#212]
The method **_itemset_** in Numpy has been gone since V2.0.

I see the file named "**FixedEndReactions**.py" in the library. It uses old API of Numpy. One of them is `itemset`. It will cause issues. You will manually remove it.

**AttributeError: `itemset` was removed from the ndarray class in NumPy 2.0. Use `arr[index] = value` instead.**

**Comment by JWock82** [comment]
This has been resolved in the `main` branch, and will be resolved in the next release. `itemset` is no longer used by `Pynite`.
