### ISSUE TITLE
Question: Getting Rendering to work (trame / pywidgets ImportError)

### ISSUE THREAD

**Issue by zxcvb2000** [JWock82/Pynite#214]
Hi all, this is probably a silly thing on my part but I get the following import error when I try to do rendering (see below). I have trame and ipywidgets installed, including pyvista, vtk etc. I have also tried this on a different computer and get the same error. I'm on Windows 10 x64, all the latest python/package install (with the exception of numpy for which I needed to install a package earlier than v2.0)

I'm wondering if I need to have VTK installed separately on windows? I remember using PyNite about 2 years ago before the pyvista implementation and back then I had to install VTK separately to get it working. Thanks.

Code:
"from PyNite.Rendering import Renderer"

Error:
"
Traceback (most recent call last):
  File "C:\Users\1\Documents\Python code\.venv\Lib\site-packages\pyvista\jupyter\__init__.py", line 46, in _validate_jupyter_backend
    from pyvista.trame.jupyter import show_trame
  File "C:\Users\1\Documents\Python code\.venv\Lib\site-packages\pyvista\trame\__init__.py", line 9, in <module>
    from pyvista.trame.jupyter import elegantly_launch
  File "C:\Users\1\Documents\Python code\.venv\Lib\site-packages\pyvista\trame\jupyter.py", line 11, in <module>
    from trame.widgets import vtk as vtk_widgets
ImportError: cannot import name 'vtk' from 'trame.widgets' (C:\Users\1\Documents\Python code\.venv\Lib\site-packages\trame\widgets\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\1\Documents\Python code\pynite_test.py", line 1, in <module>
    from PyNite.Rendering import Renderer
  File "C:\Users\1\Documents\Python code\.venv\Lib\site-packages\PyNite\Rendering.py", line 16, in <module>
    pv.set_jupyter_backend('trame')
  File "C:\Users\1\Documents\Python code\.venv\Lib\site-packages\pyvista\jupyter\__init__.py", line 113, in set_jupyter_backend
    pyvista.global_theme._jupyter_backend = _validate_jupyter_backend(backend)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\Documents\Python code\.venv\Lib\site-packages\pyvista\jupyter\__init__.py", line 48, in _validate_jupyter_backend
    raise ImportError('Please install `trame` and `ipywidgets` to use this feature.')
ImportError: Please install `trame` and `ipywidgets` to use this feature.
"

I have the following packages installed:
Package            Version
------------------ -----------
aiohappyeyeballs          2.4.0
aiohttp                   3.10.5
aiosignal                 1.3.1
anyio                     4.4.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     24.2.0
babel                     2.16.0
beautifulsoup4            4.12.3
bleach                    6.1.0
certifi                   2024.8.30
cffi                      1.17.0
charset-normalizer        3.3.2
colorama                  0.4.6
comm                      0.2.2
contourpy                 1.3.0
cycler                    0.12.1
debugpy                   1.8.5
decorator                 5.1.1
defusedxml                0.7.1
executing                 2.0.1
fastjsonschema            2.20.0
fonttools                 4.53.1
fqdn                      1.5.1
frozenlist                1.4.1
h11                       0.14.0
httpcore                  1.0.5
httpx                     0.27.2
idna                      3.8
ipykernel                 6.29.5
ipython                   8.27.0
ipywidgets                8.1.5
isoduration               20.11.0
jedi                      0.19.1
Jinja2                    3.1.4
json5                     0.9.25
jsonpointer               3.0.0
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
jupyter_client            8.6.2
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter_server            2.14.2
jupyter_server_terminals  0.5.3
jupyterlab                4.2.5
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.3
jupyterlab_widgets        3.0.13
kiwisolver                1.4.5
MarkupSafe                2.1.5
matplotlib                3.9.2
matplotlib-inline         0.1.7
mistune                   3.0.2
more-itertools            10.4.0
msgpack                   1.0.8
multidict                 6.0.5
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
nest-asyncio              1.6.0
notebook_shim             0.2.4
numpy                     1.26.4
overrides                 7.7.0
packaging                 24.1
pandocfilters             1.5.1
parso                     0.8.4
pillow                    10.4.0
pip                       24.0
platformdirs              4.2.2
pooch                     1.8.2
prettytable               3.11.0
prometheus_client         0.20.0
prompt_toolkit            3.0.47
psutil                    6.0.0
pure_eval                 0.2.3
pycparser                 2.22
Pygments                  2.18.0
PyNiteFEA                 0.0.94
pyparsing                 3.1.4
python-dateutil           2.9.0.post0
python-json-logger        2.0.7
pyvista                   0.44.1
pywin32                   306
pywinpty                  2.0.13
PyYAML                    6.0.2
pyzmq                     26.2.0
referencing               0.35.1
requests                  2.32.3
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.20.0
scipy                     1.14.1
scooby                    0.10.0
Send2Trash                1.8.3
setuptools                74.0.0
six                       1.16.0
sniffio                   1.3.1
soupsieve                 2.6
stack-data                0.6.3
terminado                 0.18.1
tinycss2                  1.3.0
tornado                   6.4.1
traitlets                 5.14.3
trame                     3.6.3
trame-client              3.2.5
trame-server              3.1.0
types-python-dateutil     2.9.0.20240821
typing_extensions         4.12.2
uri-template              1.3.0
urllib3                   2.2.2
vtk                       9.3.1
wcwidth                   0.2.13
webcolors                 24.8.0
webencodings              0.5.1
websocket-client          1.8.0
widgetsnbextension        4.0.13
wslink                    2.1.2
yarl                      1.9.6

**Comment by angelmusonda** [comment]
Hi,

It should work if you run the following:

`pip install pyvista[all,trame]
pip install ipywidgets`

Angel

**Comment by rogmet** [comment]
I had the same issue and `pip install pyvista[all,trame]` found a couple of things that weren't previously installed. The code ran fine after that so it solved mine! Thanks.

**Comment by zxcvb2000** [comment]
Hi, sorry for the delayed response. Yes the issue is resolved. You need to use the "[all]" command with pip install pyvista[all].

Thanks for the help everyone.
