### ISSUE TITLE
merge_duplicate_nodes() function does not return the list of removed nodes as expected

### ISSUE THREAD

**Issue by SteelScript** [JWock82/Pynite#219]
**Describe the bug**
The function merge_duplicate_nodes() does not return a value. It should return the variable remove_list, which contains the names of the removed nodes.

**Expected behavior**
The function merge_duplicate_nodes() should return the list of names of removed nodes as specified in the [documentation](https://pynite.readthedocs.io/en/latest/FEModel3D.html#PyNite.FEModel3D.merge_duplicate_nodes).

**Additional context**
The documentation indicates that merge_duplicate_nodes() must return the names of removed nodes. The implementation is currently missing a return statement for remove_list.

**Comment by SteelScript** [comment]
Is it possible to get the preserved node along with its deleted counterparts?

**Comment by JWock82** [comment]
This is now corrected in the main development branch. It will be included in the next release. It'd take a fair bit of "rewiring" the method to get the deleted counterparts. Right now, once the are deleted they are gone from the model.

**Comment by SteelScript** [comment]
Thank you for the quick fix! I understand that reworking the method to retrieve deleted counterparts would require significant changes. I appreciate your efforts and look forward to the next release with the bug fix included.
