### ISSUE TITLE
Allow adding existing Material objects to the model via add_material or a new method

### ISSUE THREAD

**Issue by SteelScript** [JWock82/Pynite#220]
**Is your feature request related to a problem? Please describe.**
Currently, the add_material function creates a new material each time it is called. However, there are use cases where users might want to create their own Material objects externally (e.g., from a user-defined configuration or an external database) and pass them directly to the model. As of now, there's no direct way to add an existing Material object to a model. I'm frustrated because I cannot reuse existing Material objects without rewriting or duplicating their properties when using add_material.

**Describe the solution you'd like**
I would like to see an enhancement to the add_material function (or a new function) that allows an existing Material object to be passed and added directly to the model. This could either be done by modifying add_material to check if the input is a Material object or by adding a new method like add_existing_material.

**Describe alternatives you've considered**
One alternative I've considered is manually adding the Material object to the model's materials dictionary, but this bypasses internal consistency checks (like name duplication) and requires users to know about the internal structure of the model, which is not ideal. Another alternative is creating new materials within the add_material function, but this leads to redundancy when the same material is reused in multiple models.

**Additional context**
Allowing the addition of an existing Material object would improve flexibility and code reusability, especially when materials are defined in a modular or dynamic way (e.g., from configuration files or user input). It would also align with Python's object-oriented principles by encouraging the reuse of objects rather than recreating them.

**Comment by angelmusonda** [comment]
Hi @SteelScript,

I do not understand what you mean by adding an existing material object to a model. Do you mean passing one material object from one FEModel3D to another? 

Angel

**Comment by SteelScript** [comment]
hello @angelmusonda ,

I was thinking of creating a material from the 'Material' class and then adding it to the model using the `add_material `method. But I later realized that I could create a material and add it to the model via `model.materials[name] = new_material`. However, this method does not pass the checks performed by the `add_material `method.

**Comment by angelmusonda** [comment]
Can you provide a use case in which you may want to define a material outside the model?

**Comment by SteelScript** [comment]
In my case, the user has to define materials and sections in the first part of the program where the model is not yet defined. The materials and sections are then passed as arguments to a method that creates the model and adds the members with material and section.

**Comment by angelmusonda** [comment]
I see. You may have to define your own data structure to hold all the user input, then pass it to the method that creates the model. A dictionary can be very convenient.

**Comment by SteelScript** [comment]
This is the solution I have chosen for now.
Thank you for your time.
