### ISSUE TITLE
Sign convention of internal forces

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#28]
I have already sent this comment in pull request Update BeamSegment.py #23 but I'm not sure if you can see it. 

The links you sent me haven't the same positive convention. So, in order to avoid confusion for future developing, I would like to be sure about convention used with torque.

- Using AddMemberPtLoad, is concentrated torque positive if vector is directed along positive x local axis?
- About torque reactions in the nodes, are they positive if directed along positive X global axis?
- About internal axial, shear, moment and torsion, is positive convention the one indicated in figure below take by https://knowledge.autodesk.com/support/robot-structural-analysis-products/learn-explore/caas/CloudHelp/cloudhelp/2015/ENU/Robot/files/GUID-D1195F2E-6310-4DF6-BE1E-DCCD2A0D121E-htm.html ?

**Comment by JWock82** [comment]
I've officially changed the sign convention so that all internal forces (looking to the right of a section cut) are positive when they match the local coordinate system. This is how STAAD, RAM, and RISA all do it, and it seems like the most intuitive way. I'll update the wiki soon with a sketch.

**Comment by LcnGnd** [comment]
Positive convention of external loads is important too, a sketch of this could be useful.
