### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#32]
I found a problem during an exemple test of new PyNite. There is a problem in a simple supported beam with a concentrated force acting in local y direction. The problem is about deflection.

##Units N e m

##Import `FEModel3D` from `PyNite`
from PyNite import FEModel3D
from PyNite import Visualization

##Create a new finite element model
SimpleBeam = FEModel3D()
L=5 #m

##Nodes 
SimpleBeam.AddNode("N1", 0, 0, 0)
SimpleBeam.AddNode("N2", L, 0, 0)
SimpleBeam.AddAuxNode("aN1",0,0,L/2)

##Beam (30x50 cm)
E=2.1e11 #N/m^2
G=1
Iy=0.001125 #m^4
Iz=0.003125 #m^4
J=1
A=0.15 #m^2

SimpleBeam.AddMember("M1", "N1", "N2",E,G,Iy,Iz,J,A,"aN1")

##Supports
SimpleBeam.DefineSupport("N1",True, True, True, True, False, False)
SimpleBeam.DefineSupport("N2",True, True, True, True, False, False)
view=Visualization.RenderModel(SimpleBeam,0.2)

##Loads
SimpleBeam.AddMemberPtLoad("M1","Fy",2000,L/2)#N e m
#SimpleBeam.AddMemberDistLoad("M1","Fy",10,10,2,3)

##Analysis
SimpleBeam.Analyze()

##Diagrams V,M and displacements

SimpleBeam.GetMember("M1").PlotDeflection("dy")
SimpleBeam.GetMember("M1").PlotShear("Fy")
SimpleBeam.GetMember("M1").PlotMoment("Mz")
SimpleBeam.GetMember("M1").PlotAxial()

**Comment by JWock82** [comment]
I know what went wrong. It should be corrected now.
