### ISSUE TITLE
Sign convention of external loads 

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#34]
I just viewed the image with sign convention of internal actions. And what about external loads?

**Comment by LcnGnd** [comment]
After you update of sign convention of internal actions, sign convention of external load is the same? Or it's changed too?

**Comment by LcnGnd** [comment]
Where can I find information about sign convention of external loads? It's necessary for doing analisys.

**Comment by JWock82** [comment]
Sorry this is taking so long. I've been working on other features. I'll get around to this eventually.

**Comment by JWock82** [comment]
I've added load visualization. This should clear up any confusion over how loads are applied.
