### ISSUE TITLE
3D deformed shape

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#35]
In order to obtaine 3D deformed shape, I've introduced axial deformation and axial translation in PyNite. I've defined two new functions in BeamSegZ.py: 
 
![Cattura](https://user-images.githubusercontent.com/56585383/72279577-b7eb3380-3636-11ea-913d-a56aeca385e7.JPG)

"Translation1" is defined in Member3D.py forsì SegmentsZ[0] and SegmentsZ[i].

With these new functions, deformed shape of 2D frame shown in pull request Update Visualization.py #30 now it's correct.

![ssss](https://user-images.githubusercontent.com/56585383/72280253-3694a080-3638-11ea-91de-314259b739ac.JPG)

There are some problems with axial distributed load (p1 and p2); I think because I have to add other terms (terms that includes p1 and p2) in Axial translation's formula. In this moment, using this formulation, with a simple supported beam with axial distributed load, I otained the follow axial translations:

![eee](https://user-images.githubusercontent.com/56585383/72280410-8c694880-3638-11ea-8dae-55c6561926b1.JPG)

I've tried to understand formula used in Deflection function in BeamSegZ but I don't remeber how get terms who account for distributed load p1 and p2.

Thaks for supporting!

**Comment by JWock82** [comment]
I'll post how I derived the beam segment deflection equations soon. I've been meaning to do it for a while now, along with other derivations I've used. I used direct integration to get the beam segment equations.

I used a 'Jupyter Lab' and 'Sympy' to help me get the math right. You'll need to have those two libraries installed in order to view the notebook. Or you could install the Jupyter Notebook viewer.

**Comment by LcnGnd** [comment]
But do these formulations can be found in books of Structural mechanics theory ?

**Comment by JWock82** [comment]
The equations in PyNite are derived from the direct integration method, and the slope-deflection method, which are in just about every structural engineering textbook.

The derivations have been uploaded now.

**Comment by JWock82** [comment]
Your function `AxialDeformation` appears to return the axial strain at `x`. Don't we need to sum all the axial strains up to `x` instead? It appears that's what you're attempting to do with the `self.AxialDeformation(x) * x` term. That equation works if the strain is constant, but a summation or even integration may be required for variable axial loads.

**Comment by JWock82** [comment]
In order to handle the summation, the BeamSegZ class would need a variable added to it to track initial translation on each segment, the same way we track initial deflection.

**Comment by LcnGnd** [comment]
About AxialDeformation, it should be correct; it returns axial strain at x and I need this because I also introduce the function PlotAxialDeformation that is defined in Member.py. 
About AxialTranslation, I'm agree with you. There is something that dosen't works and I think this is releated to  formulation that I've used.

**Comment by LcnGnd** [comment]
Could you explain better what you want to say about additional variable?

**Comment by LcnGnd** [comment]
Initial translation (translation1) is defined in BeamSegZ class; it's calculated in Member3D.py for i=0:

SegmentsZ[0].translation1 = d[0,0]

and for i>0:

SegmentsZ[i].translation1 = SegmentsZ[i-1].AxialTranslation(SegmentsZ[i-1].Length())

**Comment by JWock82** [comment]
I see what you've done there. `translation1` is the additional variable there that tracks the initial translation at the start of each mathematically continuous segment. That works.

**Comment by LcnGnd** [comment]
Maybe I understand where I'm wrong! In Axial translation I have to use the integral of deformation (N(x)/EA) and not 

translation1 - self.AxialDeformation(x) * x

**Comment by JWock82** [comment]
I think that's correct!

If you look at the derivations for `BeamSegZ` I posted you'll see how I integrated the distributed load to get the change in shear, and how I integrated the shear to get the change in moment, and the moment divided by EI to get the change in slope, and the slope to get the change in deflection. When you add the initial conditions to the change you get the total shear, moment, slope, and deflection. You can use the same procedure to get the axial translation. `Sympy` will even take care of the calculus for you.

**Comment by JWock82** [comment]
Also, it's worth noting that `translation1 - self.AxialDeformation(x) *x` is the integral if the load is constant. That's why it worked for constant axial forces.

**Comment by LcnGnd** [comment]
Yes, now I have understood the derivations and I have followed the same procedure for axial translation.   In this way I wouldn't need of Axial function but it can be used for axial deformation plotting. It can be also useful.

**Comment by LcnGnd** [comment]
![aaa](https://user-images.githubusercontent.com/56585383/72297762-e5e36e80-365c-11ea-88b5-8130b393bd3a.JPG)

**Comment by JWock82** [comment]
I didn't see a pull request come through for this one. Were you planning to issue one?

**Comment by LcnGnd** [comment]
Yes of course, I'll open a pull request soon!
