### ISSUE TITLE
Bug deflection 

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#36]
**Bug deflection with distributed and concentrated load in local y direction**
PyNite returns wrong deflection when distributed load "Fy" and concentrated load "Fy" are applied at the same time on an element. In case of simple supported beam, the result is the following:

![aaa](https://user-images.githubusercontent.com/56585383/72329706-849bb980-36b5-11ea-9943-39fdc10cead0.JPG)

CODE

from PyNite import FEModel3D
from PyNite import Visualization_polilinea

Beam = FEModel3D()
L=5 #m

Beam.AddNode("N1", 0, 0, 0)
Beam.AddNode("N2", L, 0, 0)
Beam.AddAuxNode("A1",0,0,L)

E=2.1e11 #N/m^2
G=1.5e11
Iy=0.001125 #m^4
Iz=0.003125 #m^4
J=1
A=0.15 #m^2

Beam.AddMember("M1", "N1", "N2",E,G,Iy,Iz,J,A,"A1")

Beam.DefineSupport("N1",True, True, True, True, False, False)
Beam.DefineSupport("N2",True, True, True, False, False, False)

Beam.AddMemberPtLoad("M1","Fy",-20000,L/2)
Beam.AddMemberDistLoad("M1","Fy", -8000,-8000)

Beam.Analyze()

Beam.GetMember("M1").PlotDeflection("dy")

**Comment by JWock82** [comment]
That is strange behavior. I'll have a look into it.

**Comment by JWock82** [comment]
It should be fixed now.

It was an error in the `BeamSegZ` when summing moments from prior beam segments. That part of the code still had the old sign convention.
