### ISSUE TITLE
About static condensation

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#39]
I have a question but I don't know if it's due to my lack of understanding. So, you told me that static condensation is used to take into account member releases and build k matrix. Instead of this procedure, can we start from full k matrix and delete rows and coloums releated to released degree of freedom? Would I obtaine the same matrix?

**Comment by JWock82** [comment]
I'm afraid it's not quite that simple. I tried that when I first started implementing end-releases and it didn't work. Static condensation is required. When you release a degree of freedom it affects the other degrees of freedom as well.

**Comment by JWock82** [comment]
Now that I'm thinking about it, you shouldn't have to do anything with static condensation to implement these changes. Static condensation occurs on the element's local matrices. The operations you're doing are to the global matrices, after static condensation has already taken place

**Comment by LcnGnd** [comment]
I think static condensation needed on global matrix in order to divide fixed degrees of freedom and unknown degrees of freedom
