### ISSUE TITLE
D function - global displacement vector

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#43]
I think there is a problem with D function in FEModel3D.py. If the starting idea was to return global displacement vector of the model, then there is a bug. Now this function returns only a part of D. 
If it is so, we would have to correct it.

**Comment by JWock82** [comment]
The code for `D` is pretty basic (below). I don't see how there could be an error in that method. Do you mean there's an error in the method that populates `self.__D`? Could you please be more specific?

    def D(self):
        """
        Returns the global displacement vector for the model.
        """
        
        # Return the global displacement vector
        return self.__D

**Comment by LcnGnd** [comment]
Sorry, I try to be more specific. Considering for example a simple supported beam with a concetrated load in the span. 

##Units N e m

from PyNite import FEModel3D
from PyNite import Visualization

##Create a new finite element model
SimpleBeam = FEModel3D()
L=5 #m

##Nodes 
SimpleBeam.AddNode("N1", 0, 0, 0)
SimpleBeam.AddNode("N2", L, 0, 0)
SimpleBeam.AddAuxNode("aN1",0,0,L/2)

##Beam (30x50 cm)
E=2.1e11 #N/m^2
G=1
Iy=0.001125 #m^4
Iz=0.003125 #m^4
J=1
A=0.15 #m^2

SimpleBeam.AddMember("M1", "N1", "N2",E,G,Iy,Iz,J,A,"aN1")

##Supports
SimpleBeam.DefineSupport("N1",True, True, True, True, False, False)
SimpleBeam.DefineSupport("N2",True, True, True, True, False, False)
Visualization.RenderModel(SimpleBeam,0.2)

##Loads
SimpleBeam.AddMemberPtLoad("M1","Fy",-2000,L/2)#N e m

##Analysis
SimpleBeam.Analyze()
Visualization.DeformedShape(SimpleBeam,100000,0.1)


##Global displacement vector for the model.
print(SimpleBeam.D())

I build model and then analyze it. At the end I want the global displacement vector of the model and I expect a vector with dimension 12x1, being the model composed of two nodes with 6 degrees of freedom each one. 
Actually in this example, D function returns me a vector of 4x1 dimension. So, is it correct D function's behaviour? Or there is a problem?

**Comment by JWock82** [comment]
It's returning displacements for only the unsupported degrees of freedom. I know how to fix this. I'll take care of it so it returns the supported degrees of freedom as well.

**Comment by JWock82** [comment]
I think I fixed this. Give it another try and let me know.

**Comment by LcnGnd** [comment]
Now it works. It returns global displacement vector.
