### ISSUE TITLE
Bending moment diagram

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#46]
**Problem**
Internal forces convention and diagramas. Starting from png uploaded in Resources folder, I would like to explain to user the convention of internal forces in order to understand internal forces diagrams. I have observed that positive convention of bending moments My and Mz it's different in the two dierction. So for the user, it can rappresented a confusion source. I try to explain better by an example.

**Example**

#Units N e m

#Import FEModel3D from PyNite
from PyNite import FEModel3D
from PyNite import Visualization

#Create a new finite element model
SimpleBeam = FEModel3D()
L=5 #m

#Nodes 
SimpleBeam.AddNode("N1", 0, 0, 0)
SimpleBeam.AddNode("N2", L, 0, 0)
SimpleBeam.AddAuxNode("aN1",0,0,L/2)

#Beam (30x50 cm)
E=2.1e11 #N/m^2
G=1
Iy=0.001125 #m^4
Iz=0.003125 #m^4
J=1
A=0.15 #m^2

SimpleBeam.AddMember("M1", "N1", "N2",E,G,Iy,Iz,J,A,"aN1")

#Supports
SimpleBeam.DefineSupport("N1",True, True, True, True, True, True)
SimpleBeam.DefineSupport("N2",True, True, True, False, True, True)
view=Visualization.RenderModel(SimpleBeam,0.2)

**#Loads - "Fy"**
![IMG_4345 - Copia](https://user-images.githubusercontent.com/56585383/73591073-4b9f7980-44ea-11ea-90f1-5befddf3390f.jpg)

SimpleBeam.AddMemberPtLoad("M1","Fy",2000,L/2)#N e m
#Analysis
SimpleBeam.Analyze()
#Diagrams V,M and displacements
SimpleBeam.GetMember("M1").PlotDeflection("dy")
SimpleBeam.GetMember("M1").PlotShear("Fy")
SimpleBeam.GetMember("M1").PlotMoment("Mz")
![1](https://user-images.githubusercontent.com/56585383/73590976-4857be00-44e9-11ea-8bdb-e711f6b249fb.JPG)
![2](https://user-images.githubusercontent.com/56585383/73590978-4aba1800-44e9-11ea-95bc-a222b2656e91.JPG)
![3](https://user-images.githubusercontent.com/56585383/73590979-4c83db80-44e9-11ea-85b0-1d0eb6e1f1c9.JPG)

**#Loads - "Fz"**
![IMG_4345](https://user-images.githubusercontent.com/56585383/73591079-5ce88600-44ea-11ea-928a-8367b79d7e4b.jpg)

SimpleBeam.AddMemberPtLoad("M1","Fz",2000,L/2)#N e m
#Analysis
SimpleBeam.Analyze()
#Diagrams V,M and displacements
SimpleBeam.GetMember("M1").PlotDeflection("dz")
SimpleBeam.GetMember("M1").PlotShear("Fz")
SimpleBeam.GetMember("M1").PlotMoment("My")

![4](https://user-images.githubusercontent.com/56585383/73590983-51488f80-44e9-11ea-83cb-05b2b1d7bbaa.JPG)
![5](https://user-images.githubusercontent.com/56585383/73590984-54438000-44e9-11ea-883b-b6304437cac9.JPG)
![6](https://user-images.githubusercontent.com/56585383/73590987-560d4380-44e9-11ea-82ba-652c51657e47.JPG)

What do you think about this?

**Comment by JWock82** [comment]
It can be confusing to have the positive bending sign convention switch on the local y-axis, but that's how both STAAD and RISA are set up, and I think it's a sign convention many users are used to. I think you've explained it very well here. I'll try to get around to including this. I've been busy implementing load combinations lately and it's been quite a task.

**Comment by JWock82** [comment]
I've added load visualization to clear up any confusion.
