### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#48]
I'm using PyNite for my master thesis and togheter with my professor we are modeling a girder bridge in order to perform linear elastic analysis and use them togheter with a monitoring system installed on the bridge. This rappresents the start of a big project. If you are agree with me, I think is correct mention you in my thesis work.

**Comment by JWock82** [comment]
I'd be honored. Thank you for your contributions and ideas too. Eventually I'd like to see more contributors helping out, but it's still a very young program that few people know about. The more eyes we get on it the better it will get. If we all contribute a little this program will do a lot!

**Comment by LcnGnd** [comment]
Who are you? I'm a civil engineering student in Polytechnic of Turin

**Comment by JWock82** [comment]
I'm a practicing structural engineer in the state of Utah in the United States. I don't like giving out too much personal information on public sites, but you can contact me at Building.Code@outlook.com if you'd like more info.
