### ISSUE TITLE
I want to help this app.

### ISSUE THREAD

**Issue by mantakeke** [JWock82/PyNite#49]
Dear JWock82,
I am studying master in civil engineering. I am related to code so I want to help your code. Could you communicate with me? mehmetfatiharat@yandex.com

**Comment by JWock82** [comment]
If you'd like to contribute, the best way is to fork this repository, which makes a copy of it in your GitHub account. You can then edit your copy of the repository and issue a "pull request" for me to pull the code you've written into this repository. That will allow me to directly compare and review the changes you've made.
