### ISSUE TITLE
PyNite installation

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#5]
I have a problem with PyNite installation.
First of all I install Pynite by the command "pip install Pynite" in prompt of comand of my computer. Now, if I check the already installed modules by the command "pip list", PyNite is available. The problem is when I want to use PyNite module in a script: 

PyNite-master -> Examples -> Simple Beam - Point Load.py -> EDIT with IDLE ->Run module (F5)

Python give me an error:
![Cattura](https://user-images.githubusercontent.com/56585383/66821099-2c340f00-ef42-11e9-83fd-cf1e8ec61319.JPG)

How can I solve it?

**Comment by JWock82** [comment]
Use ‘pip install pynitefea’ instead. The name PyNite was already taken in the PyPI package manager, so I added ‘fea’ to the end.

‘pip install Pynite’ installs some kind of ‘Fortnite’ video game package. You’ll probably want to uninstall that, unless you play Fortnite :)

**Comment by LcnGnd** [comment]
Great! Problem solved!
Thank you so much.
