### ISSUE TITLE
vtkOutput Window errors

### ISSUE THREAD

**Issue by Tarang74** [JWock82/PyNite#51]
**Describe the bug**
I ran one of the testing and debugging files with the visualisation vtk module. However, when run in terminal, the window does not show anything. There are just errors. The printed lines do work however and they give me the correct results. 

**To Reproduce**
1. Go to 'Testing & Debugging\2D Frame XY Plane - Gravity Load.py'
2. Run file in Python 3.7.7 64-bit
3. See error

**Expected behavior**
Some sort of visualisation?

**Screenshots**
![image](https://user-images.githubusercontent.com/31427635/78537280-944d1900-7832-11ea-8a36-3c88febb7c99.png)

![image](https://user-images.githubusercontent.com/31427635/78537309-a2029e80-7832-11ea-9621-ea921832d27e.png)

**Comment by JWock82** [comment]
It's working fine on my computer:
![image](https://user-images.githubusercontent.com/33323539/78566708-dcd9e780-77dc-11ea-946e-38939498543c.png)

How did you install VTK? Did you use `pip install vtk` from your command line? It almost looks like you're running a C++ version of VTK rather than a Python version.

**Comment by JWock82** [comment]
Can you confirm if this solved your problem or not?

**Comment by Tarang74** [comment]
Sorry about the long wait, I was busy the last few days. 
I used pip to install, and it installed fine for 3.7.0, but it showed the error as shown above
What version of Python are you using?

If vtk doesn't work, I'll make use of matplotlib and other modules for visualisation. I just want to know if PyNite is capable of plotting using the other modules (mpl etc.)? 
I mean the whole structure, not individual members, and showing loads/reactions/etc like when you draw a free body diagram or something.

I wanted to know so that I dont spend my time reinventing something thats already created, cause I couldn't find anything for that in the project.

Oh btw, I am using your code forked to create a GUI interface using PyQt, I'll send you a link when I have everything working. :)

**Comment by Tarang74** [comment]
!reopen

**Comment by Tarang74** [comment]
!open

**Comment by Tarang74** [comment]
!opened

**Comment by JWock82** [comment]
I'm running 3.7.7 (64 bit).

That's a really strange error. I haven't seen that one before. It looks like it has something to do with your installation of GLEW. See this [link](https://public.kitware.com/pipermail/vtkusers/2018-May/101749.html). Are you running the program on a virtual machine?

That's great that you're working on a GUI! It's something I've been wanting to work on, but I've been working on so many other pieces of this program that I haven't gotten around to it yet. This has been a lot of work for one person and I could use all the help I can get. Send a pull request when you're ready and I'll get it incorporated.

**Comment by JWock82** [comment]
I'm still curious... Did you ever get this problem solved?

**Comment by Tarang74** [comment]
> I'm still curious... Did you ever get this problem solved? I want to make sure other users aren't having similar experiences.

I am not worried about it now, as I am developing my own app using matplotlib. I have forked my progress so far, you can see it on my account. Using the latest version of Python, you can currently add nodes, materials and members, and see it appear live on a plot when you submit.

I will work on adding loads, supports (nodal, member) and then work on optimising the app, (say, if its only 2d etc.) 

Please check it out and give me any feedback. I’ll be working on it here and there, since school started again, although my assignments have been cancelled so I have more time to work on this project.

I have tried to incorporate every aspect of PyNite into my app, and currently am only using FEModel3D. 
Thanks for letting me use your program for this, I think yours is probably the best one I found on GitHub.
