### ISSUE TITLE
Support Springs

### ISSUE THREAD

**Issue by radiohalo123** [JWock82/PyNite#54]
The ability to add a spring support directly to a node rather than creating a new spring element might be helpful to many users.

The DefineSupport function could be setup to somehow take true, false, or a spring stiffness value. 
Example:       ABCD.DefineSupport('N1', False, True, **1153**, True, True, True)

A good example is the skyciv implementation allowing you to add a stiffness for all 6dofs
![image](https://user-images.githubusercontent.com/17434716/80734437-2c11f000-8add-11ea-817e-0cc556c811fc.png)

**Comment by JWock82** [comment]
It's been my plan to implement this feature. I just haven't gotten around to it yet as there are many other features I'd like to implement first. I don't think it'd be too difficult to do though. Reporting is the next feature I'd like to implement. If you'd like to expedite it you can fork the code and implement it yourself and then issue a pull request.

**Comment by radiohalo123** [comment]
Unfortunately I am very new to Python and don't feel I would be very effective. I develop mostly in .net framework and as an engineer have a general interest in finite structure modeling. I have been studying your code and think it is one of the cleanest I have seen in any programming language. What book do you reference? My opinion is that support springs would be a more useful (high priority) feature than reporting for most users whom are already formatting the results in the way that suits them best for their needs. Overall GREAT WORK!

**Comment by JWock82** [comment]
I'll have a look at getting it implemented sooner if it's simple. I think it may be as simple as adding a stiffness value to the stiffness matrix, but I'll have to pull out the textbooks to make sure.

I've built PyNite using several references, notes from structural analysis and finite element classes I took in college, and internet searches.

The books I've used are:

-"A First Course in the Finite Element Method, 4th Edition" by Daryl L. Logan
- "Structural Analysis, 3rd Edition" by Aslam Kassimali
- "Matrix Structural Analysis, 2nd Edition" by William McGuire, Richard H. Gallagher, and Ronald D. Ziemian
- "Theory of Matrix Structural Analysis" by J.S. Przemieniecki
-"Finite Element Analysis Fundamentals" by Richard H. Gallagher

2 years ago I didn't know Python either. I built a little program for Excel using VBA (see xlFrame), and I wanted it to do more. I had a background in C++ so I started learning C#, XAML and the .NET framework. Then I discovered Python and was blown away by the open source scientific and engineering libraries that were available. Coming from VBA and C#, Python was easy to pick up in no time.

**Comment by JWock82** [comment]
Springs have been added. For now, you'll have to use spring elements to build your own support springs. At some future point I may incorporate them directly into the supports.

**Comment by JWock82** [comment]
Update: I’ve begun working on this feature. After running some preliminary tests it seems to be working as expected. I need to polish it a little more and run more tests, but I should have this feature up and running in the next week, if not the next few days.

**Comment by JWock82** [comment]
This feature is now available as of version 0.0.40.
