### ISSUE TITLE
Typo in function AddNodeDisplacement

### ISSUE THREAD

**Issue by tamalone1** [JWock82/PyNite#56]
In `FEModel3d.py`, the line below (line 231) has a typo in the assignment. The value is assigned to `node.EnforceDX` instead of `node.EnforcedDx`. This is a silent error that prevents displacements from being applied in the 'DX' direction at all. The error is silent because the assignment still happens, but to the wrong attribute name.

https://github.com/JWock82/PyNite/blob/ec049d222e7f4b423ca6cd2762cb8dff0b4b6a1d/PyNite/FEModel3D.py#L231

**Comment by JWock82** [comment]
Thanks for reporting this. I've fixed it in the repository. I'll fix it on PyPi soon as well.
