### ISSUE TITLE
Does the current PyNite module support following features

### ISSUE THREAD

**Issue by Udayaprasad** [JWock82/PyNite#61]
**Does the current PyNite module support following features?**

- Spring-Tension Only/Compression Only
- Rigid Elements for connection
- Temperature Load Application

**Comment by Udayaprasad** [comment]
@JWock82  Could you please help us with the above requirement? I am new to structural engineering, and I am from software engineering background. I don't know about the 3D structural analysis and its internals to write the code.

Thanks,
Uday

**Comment by JWock82** [comment]
What your looking for is incredibly technical and complex. What type of nonlinearity are you looking for? Geometric nonlinearity or material nonlinearity. PyNite is a linear and nonlinear-**elastic** solver. If you want to take problems into the material non-linear (inelastic) range you'll need a different package.

- At some point I'll probably add spring supports, but for now springs can be modeled by recognizing that the axial "spring" stiffness of a member is EA/L and adjusting the properties of "dummy" members to provide the stiffness you want. Beam and columns are in reality just really stiff springs.
- Similarly, rigid elements can be created from "dummy" beam elements by setting the Iy, Iz, and A properties to really high values relative to everything else. 
- Thermal loads would not be difficult to add to PyNite. I just have been focusing on other priorities. 

From your StackOverflow thread, it looks like you're trying to do connection design. Finite element analysis (FEA) is rarely the best choice for connection design unless your doing something really obscure like [this](https://www.arcat.com/catalogs/castconn/productcatalog-2019/index.html?coid=48577l). Finite element analysis is great at giving you pretty looking bad answers, so you really need a strong background in FEA to interpret the results.

Other methods of analysis based on mechanics of materials principles, research and testing, and engineering standards (e.g. AISC 358) are the normal way to handle most connection designs. Connection types are usually governed by the overarching building code.

If you're looking for open source software, you may want to look into FreeCAD, which allows you to model complex parts and then mesh and analyze them. You'll need to be familiar with parametric modeling techniques to use it. It uses Calculix to analyze models. The analysis features are pretty limited. I think it may be able to hand some types of nonlinear problems. FreeCAD has a Python command line interface and supports Python scripts.

Based on your question, I recommend you have someone with a lot of connection design experience help you. Connection failures are often deadly.

**Comment by Udayaprasad** [comment]
@JWock82  Thank you for your comments. 
I will talk to my team and share your suggestions.

**Comment by Udayaprasad** [comment]
@JWock82  
We are facing a major blocker in implementing a FEM model for structural analysis. 
We think PyNite solves all our problems except for modelling tension-only/compression-only spring elements.
It would be of great help if my team and I could talk to you and get your inputs on our implementation strategy. Please let me know if this is fine so that I can share my e-mail address. 
Thank you.

**Comment by JWock82** [comment]
Go ahead and e-mail me and I'll respond.

**Comment by Udayaprasad** [comment]
Hi Craig,

This is my email ID: *uvakalapudi@innominds.com <uvakalapudi@innominds.com>*
(or) *uday.vakalapudi@gmail.com <uday.vakalapudi@gmail.com>*

Just wanted to reiterate our blockers in implementing a FEM model

*Major Blocker:*

Unable to model tension-only/compression-only spring elements.

We do see having options of just springs but we are specifically
looking for tension-only/compression-only features.

*Good to have:*

Rigid elements for connection

Temperature load application

(These are not our prime blockers because we can have manual
turnaround for these problems)

Any help on our spring modelling issue will be much appreciated. Can you
suggest sometime in your timezone, so that I will ask my team members to
available for the call?

Looking forward to hearing from you.

Thanks again for your time.

Thanks,
Uday

**Comment by Udayaprasad** [comment]
Thank you, @JWock82 . Your help is really added to the work we are doing currently.
