### ISSUE TITLE
Bug: AISC 2nd Order Benchmark Check doesn't return the expected values

### ISSUE THREAD

**Issue by tamalone1** [JWock82/PyNite#63]
**Description:**
The calculated values for the moment and deflection do not match the expected values printed at the end.

**To Reproduce:**
1. Run `Testing & Debuging/AISC 2nd Order Benchmark Check.py`
2. See value mismatch in the console output.

**Output Displayed:**
```python
PyNite Calculated Moment:  -99.99499999998429
PyNite Calculated Displacement:  7.944827586205967
AISC Benchmark Problem Moment:  435.6165910296658
AISC Benchmark Problem Displacement:  40.27399092355989
```

**Comment by JWock82** [comment]
I'll have a look. I think I know what may have caused this. I recently added a tension-only/compression-only analysis feature to the Analyze_PDelta method that may have thrown this off. It used to work. Thanks for reporting the bug. I'll try to fix it when I get some time this weekend.

**Comment by tamalone1** [comment]
Would you be interested in automated tests based on this script, and the others in `Testing & Debuging`? Exploring that idea was how I found this bug.

**Comment by JWock82** [comment]
That would be nice to have those automated. I'm sure several of the tests are broken after I added load combinations. I haven't gotten around to updating all of them.

**Comment by JWock82** [comment]
I fixed it. It's working properly now. I also updated the AISC benchmark test to match the new member sign convention I implemented a while back.

**Comment by JWock82** [comment]
I noticed this is in its own "tests" folder. It makes sense to me to place this in the "Tests & Debugging" folder. If you have no objections I'm going to move it there.

**Comment by tamalone1** [comment]
Moving it to a different folder is fine. Just be aware that in `tests/__init__.py`, [Line 16](https://github.com/JWock82/PyNite/blob/61a11895930f266fc09525eaa573b7ae27cc5e0d/tests/__init__.py#L16) uses the folder name. The argument to `loader.discover` would have to be updated.

**Comment by JWock82** [comment]
I've moved it into `Testing & Debugging` and set it up to run from there. It will look for any python file that begins with `test_`. In the future I think it would make sense to set up each test file as subclass of `TestCase`. So many features to add so little time :)

**Comment by tamalone1** [comment]
I can work on converting the test scripts to TestCases. The 
visualization and reporting parts will be tricky, though. I don't see 
how to check their results without physically looking at the output.
