### ISSUE TITLE
Possibly wrong FEM solution for a problem

### ISSUE THREAD

**Issue by AhmadTowaiq** [JWock82/PyNite#66]
**Description**

I have tried to solve a 2D frame example using your code using two software packages in addition to this one. The results obtained using PyNite are different from those obtained using the other two software. I think there is a mistake in the FEM procedure implemented. Please confirm.

**To Reproduce**
1. Run the attached PyNiteCode.Docx
2. Find the results printed in the Python console

**Expected behavior**
When run in the two other softwares the results are different. See MyResults.jpeg

**Screenshots**
See a screenshot of the PyNite results in PyNiteResults.jpg
Also see the original problem statement I am trying to solve in ProblemStatement.jpeg

**Additional context**
Please let me know. Kindest regards. Ahmad

[PyNiteCode.docx](https://github.com/JWock82/PyNite/files/5321875/PyNiteCode.docx)
![MyResults](https://user-images.githubusercontent.com/68343279/94994805-cac9dd80-05a2-11eb-8ce3-2a5d3813b302.png)
![ProblemStatement](https://user-images.githubusercontent.com/68343279/94994807-ce5d6480-05a2-11eb-8a96-196f54e780aa.jpeg)
![PyNiteResults](https://user-images.githubusercontent.com/68343279/94994809-d3221880-05a2-11eb-88ae-2a99e14a9afa.png)

**Comment by JWock82** [comment]
You have I2 and G swapped in your "AddMember" functions. Iz is set to 100 and G has been set to I<sub>1</sub>, I<sub>2</sub>. It should look like this:

![image](https://user-images.githubusercontent.com/33323539/94995714-66d0f600-055d-11eb-9b5f-aecfc5805223.png)


When I correct it I get your answers above exactly:

![image](https://user-images.githubusercontent.com/33323539/94995703-4f920880-055d-11eb-9bf3-8c5303feb945.png)

**Comment by AhmadTowaiq** [comment]
Thank you very much. I appreciate you spotting my mistake. Best,
