### ISSUE TITLE
How to install it. Thanks

### ISSUE THREAD

**Issue by nicolasastroza** [JWock82/PyNite#67]
Hi, I downloaded the files but I can not make them work. When I run a python file using PyNite module, an error raise telling that there is not module named PyNite. I hope you can help me to install ir right, thanks.
Best regards

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Tarang74** [comment]
Is the import setting properly set?

**Comment by tamalone1** [comment]
To use the files from Github, you will need to install them using pip. You would go to the directory with the files in it, and type:
`pip install -e \path\to\folder\PyNite`

However, this requires a `setup.py` to be included in the repository, which isn't the case now. When I installed it on my machine I wrote a basic one myself.

```
from setuptools import setup

setup(name='PyNite',
      license='MIT',
      packages=['PyNite'])
```

**Comment by JWock82** [comment]
I'll add the setup file to the repository.

**Comment by JWock82** [comment]
I'm unfamiliar myself with installing it the way tamalone1 suggests, but I've added my setup file to the repository if that helps. This is the one I use whenever I upload a new version to PyPI.

It sounds to me like you don't have PyNite installed in a location recognized by your PYTHONPATH variable.

**Comment by JWock82** [comment]
See also the wiki:

[https://github.com/JWock82/PyNite/wiki/1.-Getting-Started](https://github.com/JWock82/PyNite/wiki/1.-Getting-Started)

**Comment by JWock82** [comment]
Did this get resolved? I'd like to close out this issue.
