### ISSUE TITLE
About Member3D.py

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#7]
In this part of the script distributed axial load (p1,p2) is calculated for each Segment by using distributed transverse load (w1,w2). Is it correct? 
There is also a note in the script about w1 and w2. 

![Cattura](https://user-images.githubusercontent.com/56585383/67506529-7da07480-f68d-11e9-9eb9-c9f105fd1c7d.JPG)

**Comment by JWock82** [comment]
It is correct, although I should probably rewrite it to be clearer. In this case, w1 and w2 store the magnitudes (start and end) of a distributed load, whether it's transverse or axial.

**Comment by LcnGnd** [comment]
If I have understood, using w1,w2 or p1,p2 is not important, because when I define a new distributed load it can be transverse or axial. They are only two different names

**Comment by JWock82** [comment]
Correct. Whether it's axial or transverse, the equation describing the magnitude of the load as a function of the position along the beam is still a linear equation, so the variable names don't really matter. I could have used p1 and p2 for the names, but it would have taken a few extra lines of code.
