### ISSUE TITLE
Hey sorry about the last one, but now I'm having an issue with importing pynite itself I even restarted the kernel after importing and i checked my sys.path also, Please help

### ISSUE THREAD

**Issue by AD1D1** [JWock82/PyNite#74]
![image](https://user-images.githubusercontent.com/66953528/98390161-03197b80-207b-11eb-87c6-c25265464a5a.png)

**Comment by JWock82** [comment]
Sounds like it's not installed on your PYTHONPATH. Python's PYTHONPATH variable tells python where to look to find installed packages. You can either move PyNite to the correct folder, or add PyNite's location to your PYTHONPATH variable.
