### ISSUE TITLE
Support reaction gives wrong value

### ISSUE THREAD

**Issue by linokl** [JWock82/PyNite#75]
**Describe the bug**
Hi..thank you for your brilliant work. I have been working on creating a website to do structural analysis using PyNite (www.standardsolver.com). I came across this error. I checked whether it is something on my end but no luck. I also modified the example file and manage to reproduce the same error.

The error is regarding the support reactions.

**To Reproduce**
So for a simply supported beam 5m long with a moment of 10kNm at the midpoint. I am getting a Fy support reaction of 2kN on the left side and 0.5kN on the right side. 

**Expected behavior**
I was expecting +2kN on left and -2kN on right.

**Screenshots**
The below is the screenshot from program i made using PyNite:
![image](https://user-images.githubusercontent.com/20646443/98670269-61c84900-234a-11eb-9467-4eca2ac0ca77.png)
Screenshot of modified example file:
![image](https://user-images.githubusercontent.com/20646443/98672812-4b23f100-234e-11eb-8842-4ce876709b9a.png)

Result from another program
![image](https://user-images.githubusercontent.com/20646443/98686956-1705fb80-2361-11eb-964b-d34164cb9b30.png)

**Additional context**
For other load scenarios such as point loads and udls I haven't noticed any error.
Version I am using is PyNiteFEA==0.0.21

**Comment by JWock82** [comment]
Thanks for reporting it. I'll have a look as soon as I get a moment.

**Comment by JWock82** [comment]
I think I have it fixed. I left a 6 multiplier off of the moment fixed end reaction calculations. Try it now and let me know if it works.

**Comment by linokl** [comment]
Thanks for fixing it so fast. I can confirm it is working now and giving right reaction loads.

![image](https://user-images.githubusercontent.com/20646443/98791377-e2478200-23fc-11eb-876e-5947429b59c6.png)
