### ISSUE TITLE
Hinge in a beam (Solution not convering) "Matrix is exactly singular"

### ISSUE THREAD

**Issue by linokl** [JWock82/PyNite#77]
Hi Craig,

I am trying to model the below problem as part of my digital tool development. I wanted to understand how I can model a hinge in a beam. PyNite solves the problem when there is no hinge but as soon as I introduce hinge, it is failing with "Matrix is exactly singular" warning.

![image](https://user-images.githubusercontent.com/20646443/98971151-b4e7fa80-2508-11eb-9e87-dd39be5718ec.png)

See the code for the above problem below. I did increase the member length by a factor of 10 to improve the visualization. I tried a few options but no luck so far. Am I missing something?

from PyNite import FEModel3D

SimpleBeam = FEModel3D()

SimpleBeam.AddNode('A', 0, 0, 0)
SimpleBeam.AddNode('B', 50, 0, 0)
SimpleBeam.AddNode('C', 80, 0, 0)
SimpleBeam.AddNode('F', 140, 0, 0)

SimpleBeam.AddMember('AB', 'A', 'B', 29000, 11400, 100, 150, 250, 20)
SimpleBeam.AddMember('BC', 'B', 'C', 29000, 11400, 100, 150, 250, 20)
SimpleBeam.AddMember('CF', 'C', 'F', 29000, 11400, 100, 150, 250, 20)

SimpleBeam.DefineSupport('A', True, True, True, True, False, False)
SimpleBeam.DefineSupport('C', True, True, True, False, False, False)
SimpleBeam.DefineSupport('F', True, True, True, False, False, False)

SimpleBeam.DefineReleases('AB', False, False, False, False, False, False, \
                                False, False, False, False, False, True) #Relesing moments  in z plane at B end of AB
SimpleBeam.DefineReleases('BC', False, False, False, False, False, True, \
                                False, False, False, False, False, False) #Relesing moments in z plane at B end of BC

SimpleBeam.AddMemberDistLoad('AB', 'Fy', -0.01, -24, 0, 50)
SimpleBeam.AddMemberPtLoad('CF', 'Fy', -45, 20)
SimpleBeam.AddMemberPtLoad('CF', 'Fy', -60, 40)

SimpleBeam.Analyze()

SimpleBeam.GetMember('AB').PlotMoment('Mz')
SimpleBeam.GetMember('BC').PlotMoment('Mz')
SimpleBeam.GetMember('CF').PlotMoment('Mz')

from PyNite import Visualization
Visualization.RenderModel(SimpleBeam, text_height=5, deformed_shape=False, deformed_scale=100, render_loads=True)`

Regards
Lino

**Comment by JWock82** [comment]
The problem is that you have released the moment in both beams where they attach to node B. Your model is locally unstable. This can be a difficult concept to grasp.

Think of it this way: what would happen if you applied a nodal moment to node B? Where would it go? The node would just "spin" because the moment can't go into member AB or BC. You should only model the release on one of the members framing into the node to correctly simulate the hinge.

**Comment by linokl** [comment]
Hi Craig,
It is working now and gave me right result. I will send you the link once I have finished the web page to do the beam analysis. Thank you very much. It may take one more week to finish.
