### ISSUE TITLE
pynite in action

### ISSUE THREAD

**Issue by linokl** [JWock82/PyNite#79]
Hi Craig,
Sorry to write this as a feature request. I don't know how to message in github. The beam analysis website powered by pynite is online.

https://www.standardsolver.com/beam-analysis

Please let me know if you have any comments to standardsolver@gmail.com.

Regards
Lino

**Comment by linokl** [comment]
if possible can you also change the pip install code as shown below because the user might install an older version of the module, which happened to me when I was doing the installation on the server side.

![image](https://user-images.githubusercontent.com/20646443/99544494-485b7880-29ac-11eb-9eea-97a3ca2d7d74.png)


https://pypi.org/project/PyNiteFEA/0.0.13/

**Comment by JWock82** [comment]
Very cool. Thanks for sharing. At some point I'd like to get a list going of software powered by PyNite to showcase what it's capable of. Would you mind if I added your program to the list with a link?.

**Comment by linokl** [comment]
Please feel free to add the program. Next, I am thinking of looking into 2D frame analysis (maybe 3D).
