### ISSUE TITLE
Bug: VisNode does not render as a cone if pin-supported

### ISSUE THREAD

**Issue by tamalone1** [JWock82/PyNite#85]
The `elif` expression on Visualization.py line 828 is identical to the preceding `if` expression, meaning that it never runs. This `elif` branch is intended to identify a pin-supported `Node` and render it as a cone instead of a sphere. As written, any pin-supported `Node` is rendered as a sphere as normal, through the `else` clause.

The `elif` expression should be changed to correspond to a pin-support (e.g. `SupportMX = False, ...`, etc), or removed if the cone rendering isn't desired.

https://github.com/JWock82/PyNite/blob/6d61dc76ce5683d5774b3806ae046564f9b48b13/PyNite/Visualization.py#L828

**Comment by JWock82** [comment]
I reorganized that code recently to simplify it. I likely created this bug when I did that. I'll fix it when I get a moment.

**Comment by JWock82** [comment]
This should be fixed now. Thanks for reporting it.
