### ISSUE TITLE
Problems installing using Pipfile on Windows

### ISSUE THREAD

**Issue by sadlermike** [JWock82/PyNite#86]
**Describe the bug**
When installing pynite using the Pipenv file, you get errors when trying to import the package.

The problem appears to be that pip installs the package to ...\site-packages\pynite, but the package's __init__ file contains the line:

from PyNite.FEModel3D import FEModel3D

This appears to be a case sensitivity issue - is the package intended for Linus use only?

**To Reproduce**
1. Copy pip install name from https://pypi.org/project/PyNiteFEA/
2. Add the line "PyNiteFEA = "*"" to the Pipfile
3. Run pip upgrade
4. Attempt to import pynite using either "import pynite" or  "import PyNiteFEA" or "import PyNite".

**Expected behavior**
The ability to import elements of pynite

**Screenshots**

**Additional context**

**Comment by tamalone1** [comment]
I'm not familiar with using pipenv to install. But if you use `pip install PyNiteFEA` as listed on PyPI, it should install on Windows. Once installed, it can be imported under the name `PyNite` as seen in the init.py. The imported names `PyNite` and `FEModel3D` are case-sensitive, like all module names in Python.

Does that help? If not, maybe you can give more detailed steps to recreate the problem?

**Comment by sadlermike** [comment]
Hello @tamalone1 ,

Thanks for that.  I've just had an experiment, and the problem seems to have been that I absentmidedly installed the **other** pynite (https://pypi.org/project/pynite/), and what I think happened was that when pipenv went to install PyNite, it found the existing pynite folder, and used that.

When I deleted the 'pynite' folder, it installed correctly.

Thanks for your response!

Best regards,

Mike
