### ISSUE TITLE
Coordinate Transformation

### ISSUE THREAD

**Issue by linokl** [JWock82/PyNite#88]
Hi Graig,

Hope you are doing good. I have included a module to analyse 2D frames/Trusses in standardsolver using PyNite. Link below:

https://www.standardsolver.com/frame

I had some trouble with element UDL loads, converting them from the global coordinate system to local coordinate, also to convert deflection results from local coordinates to global coordinates. I have found some solutions, but not fully confident about it when the element is oriented in the 2nd, 3rd or 4th quadrant and different element directions. I am doing the testing at the moment. I saw your previous comment on an enhancement issue about using the element transformation matrix to do the conversion. Can you point me to any reference in a book I can understand the transformation matrix you have used and which rows and columns of the transformation matrix I need to use to convert local deflections to global deflections?

Currently, I am using the following transformation matrix:

![image](https://user-images.githubusercontent.com/20646443/109787658-5dc87b80-7c06-11eb-964f-fcde8978a4a7.png)

This works for now but not very confident about it for various element orientations.

Best wishes
Lino

**Comment by JWock82** [comment]
Sorry it's taken so long to get back to you. Glad to see your app is coming along. Very impressive. You should be able to put your global forces into matrix format `F = [[FX, FY, FZ, MX, MY, MZ]]` and then multiply them by the inverse of the first 6 rows and columns of the transformation matrix to convert them to local forces. I haven't tested the code below, but I think it would look something like this:

    # Get the first 6 rows and columns of the transformation matrix
    T = my_member.T()[0:6][0:6}

    # Get the inverse of the transformation matrix
    T_inv = numpy.linalg.inv(T)
    
    # Convert global forces to local forces
    f = numpy.matmul(T_inv, F)

**Comment by linokl** [comment]
Thank you for your help. I think I have fixed the issue..need more testing.

Regards
Lino
