### ISSUE TITLE
Interchanged displacement values?

### ISSUE THREAD

**Issue by cmoha** [JWock82/PyNite#89]
Hello and good day,
Are these displacement values interchanged? i.e delta1y is swaped with delta1z.

https://github.com/JWock82/PyNite/blob/fad7deb88bb9d230ebad1405fbc116e8f60047ab/PyNite/Member3D.py#L1448-L1451

**Comment by JWock82** [comment]
No. `SegmentsZ` tracks bending about the local z axis, which produces deflection in the y axis. Similarly, `SegmentsY` tracks bending about the local y-axis, which produces deflection in the z axis.

**Comment by cmoha** [comment]
Thank you. Kindly, Can yo add some tests for deflections under various load types?
