### ISSUE TITLE
Girder bridge application

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#9]
Is it possible modify this project and solve 3D frame (girder bridge)? I need to use for example continuity supports, multi span beams, bending moment and shear diagrams in a 3d frame etc..ple

example (Girder bridge)
![Cattura](https://user-images.githubusercontent.com/56585383/67527236-d5070a80-f6b6-11e9-80f3-28e8f23da400.JPG)

**Comment by JWock82** [comment]
I can’t really tell exactly what you’re trying to model there. PyNite will do 3D linear elastic analysis for frame elements with or without end releases. Please use it with caution, and don’t substitute the results you get for engineering judgment and experience. A lot of testing is still ongoing with this relatively new project.

**Comment by LcnGnd** [comment]
Do I need to change scripts (FEModel3d.py, Member3D.py, BeamSegment.py etc..) if I want to model a 3D frame like the previous picture?

**Comment by JWock82** [comment]
You should be able to model a 3D frame with multispan beams without any modification to the scripts. Just be aware that most design codes require a second order analysis. For a moment frame structure like the one you're showing that will be critical to a safe design.

You can approximate second order effects with a linear elastic analysis, but you have to know how to do it properly. For steel, it usually means setting up multiple models: a nonsway gravity load model, and a sway lateral load model. See Appendix 7 of the AISC Specification for Steel Buildings (a free download on AISC's website) for instructions on how to do it correctly. It may be different depending on the code or material you're designing for.

**Comment by LcnGnd** [comment]
Thanks for answer.
