### ISSUE TITLE
Accuracy Of Frame Loading

### ISSUE THREAD

**Issue by SoundsSerious** [JWock82/PyNite#94]
Hi! First off awesome library, I wrote something like this back in college but this is way more slick! 

I'm integrating this library along with `sectionproperties` in my engineering library (has a google drive /sheets integration) as a one stop shop for structures info, and accuracy is important here so I have started writing a few test cases. 

A simple example, first one on this page is the test case for the following: https://engineeringlibrary.org/reference/trusses-air-force-stress-manual. Most of the beams pass their expected value, so i think i've got the general layout right but i want to get this right to prove its correct. I'm almost certain that this is related to a Release I'm not defining however I don't quite follow their use in the case of trusses

The following fails with, these are nodes directly between A-E, which are constrained:
```
fails A_G max_axial| 191.57547 == -926.00000?
fails F_G max_axial| -575.19970 == -1734.00000?
fails C_G max_axial| -385.57857 == 1541.00000?
fails E_F max_axial| 383.62423 == -770.00000?
```

Here's the minimal example, pardon the syntax wrapping, but i think you'll follow

Full code is here: https://github.com/SoundsSerious/ottermaticslib/blob/geometry/ottermatics/structure.py

```
    class test_truss(unittest.TestCase):
        #Match this example, no beam stresses
        #https://engineeringlibrary.org/reference/trusses-air-force-stress-manual

        def setUp(self):

            self.st = Structure(name = 'truss')
            self.st.add_node('A',0,0,0)
            self.st.add_node('B',15,30* sqrt(3) / 2,0)
            self.st.add_node('C',45,30* sqrt(3) / 2,0)
            self.st.add_node('D',75,30* sqrt(3) / 2,0)
            self.st.add_node('E',90,0,0)
            self.st.add_node('F',60,0,0)
            self.st.add_node('G',30,0,0)

            pairs = set()
            Lmin = 30 * sqrt(3) / 2
            Lmax = 30.1

            for n1 in self.st.nodes.values():
                for n2 in self.st.nodes.values():
                    
                    L = numpy.sqrt((n1.X - n2.X)**2.0 + (n1.Y - n2.Y)**2.0 + (n1.Z - n2.Z)**2.0)

                    if L >= Lmin and L <= Lmax and (n1.Name,n2.Name) not in pairs and (n2.Name,n1.Name) not in pairs:
                        pairs.add((n1.Name,n2.Name))
                    
                    elif (n1.Name,n2.Name) in pairs or (n2.Name,n1.Name) in pairs:
                        pass

            self.beam = sections.RectangularSection(0.5,0.5)
            

            constrained = ('A','E')
            for n1,n2 in pairs:
                bkey = f'{n1}_{n2}'
                self.bm = self.st.add_member(bkey,n1,n2,material = ANSI_4130(), section = self.beam )
               

            self.st.add_constraint('A',con_DX=True, con_DY=True, con_DZ=True, con_RY=True,con_RX=True,con_RZ=True)
            self.st.add_constraint('E',con_DX=True, con_DY=True, con_DZ=True, con_RY=True,con_RX=True,con_RZ=True)
                
            self.st.frame.AddNodeLoad('F','FY',-1000)
            self.st.frame.AddNodeLoad('G','FY',-2000)

            self.st.analyze(check_statics=True)

            print(self.st.node_dataframes)

        def test_reactions(self):

            df = self.st.node_dataframes['Combo 1']

            dfa = df[df['name']=='A']
            dfe = df[df['name']=='E']

            self.subtest_assert_near(float(dfa['rxfy']), 1667)
            self.subtest_assert_near(float(dfe['rxfy']), 1333)
            
            self.subtest_member('A','B','max_axial',1925)
            self.subtest_member('A','G','max_axial',-926)
            self.subtest_member('B','C','max_axial',1925)
            self.subtest_member('B','G','max_axial',-1925)
            self.subtest_member('C','D','max_axial',1541)
            self.subtest_member('F','G','max_axial',-1734)
            self.subtest_member('C','F','max_axial',382)
            self.subtest_member('C','G','max_axial',-382)
            self.subtest_member('C','G','max_axial',1541)
            self.subtest_member('D','F','max_axial',-1541)
            self.subtest_member('E','F','max_axial',-770)
            
            #Visualization.RenderModel( self.st.frame )

        def subtest_member(self,nodea,nodeb,result_key,truth,pct=0.025):
            key_1 = f'{nodea}_{nodeb}'
            key_2 = f'{nodeb}_{nodea}'
            
            if key_1 in self.st.beams:
                key = key_1
            elif key_2 in self.st.beams:
                key = key_2
            else:
                raise

            value = self.get_member_result(nodea,nodeb,result_key)
            dopasst = abs(value-truth) <= abs(truth)*pct

            if not dopasst:
                print(f'fails {key} {result_key}| {value:3.5f} == {truth:3.5f}?')
            self.subtest_assert_near(value,truth,pct=pct)


        def subtest_assert_near( self, value, truth, pct=0.025):
            with self.subTest():
                self.assertAlmostEqual( value, truth, delta = abs(truth*pct))
            
        
        def get_member_result(self,nodea,nodeb,result_key):
            key_1 = f'{nodea}_{nodeb}'
            key_2 = f'{nodeb}_{nodea}'

            if key_1 in self.st.beams:
                mem = self.st.beams[key_1]
                if result_key in mem.results:
                    return float(mem.results[result_key])
            
            elif key_2 in self.st.beams:
                mem = self.st.beams[key_2]
                if result_key in mem.results:
                    return float(mem.results[result_key])
                
            return numpy.nan #shouod fail, nan is not comparable
            ```

**Comment by JWock82** [comment]
I'm having a hard time seeing where your end-releases are being applied in the code above.

This sounds like it might be a nodal instability in the model. End releases are tricky to model correctly. A lot of commercial software "helps" the user out when nodal instabilities are discovered by automatically creating weak springs. PyNite doesn't do that at this point. 

Remember that every node has 6 degrees of freedom (ways it can move): 3 translations and 3 rotations. If even one of those degrees of freedom is not tied down to something you'll get erroneous results or the model won't solve. There are 2 ways to tie down a degree of freedom: (1) to a member, or (2) to a support. If every member framing into an unsupported node has end releases the node will be free to spin. If you were to apply a moment to the node where would it go? I always leave one member with full fixity at the end. It will still act like a truss member since everything else framing into the node is released.

Another option is to just use spring members instead of frame members. Set the stiffness k = A*E/L.

**Comment by SoundsSerious** [comment]
> I'm having a hard time seeing where your end-releases are being applied in the code above.
Ha fair, yea i just made it public and I need to learn how to setup a good library like yours. 

Thanks for the explanation about the nodal constraints / releases. I definitely think that's where the problem lies here, two fully constrained end nodes A/E might be warping the force transmission. I should try a pin / roller i think.  

You make mention of using DefineReleases for truss members. I think thats whats confusing me here, I would think a truss would function the same without any additional releases aslong as its providing stiffness from nodes i->j? Perhaps my confusion comes from the syntax of a truss?

I owe you an in library example before abusing your issue inbox, but maybe we can get a good test case out of this one?

**Comment by SoundsSerious** [comment]
Ok quick update to the constraints to a pin / roller system eliminates all but two failures, but one is very close:
```
fails A_G max_axial| -960.61559 == -926.00000?
fails C_G max_axial| -384.65383 == 1541.00000?
```

**Comment by JWock82** [comment]
To turn a frame member into a truss member you just need to release the rotational degrees of freedom at each end of the member. Here's some psuedo-code that will turn any member into a truss member:

model.DefineReleases('MemberName', Dxi=False, Dyi=False, Dzi=False, Rxi=False, Ryi=True, Rzi=True, Dxj=False, Dyj=False, Dzj=False, Rxj=False, Ryj=True, Rzj=True)

Keep in mind that unless the node has rotational support, at least one member framing into the node should have no releases set to True at that node.

**Comment by SoundsSerious** [comment]
Awesome! I'll have to play around with that! So a "Truss" is essentially a member with pinned end connections? Ok that makes sense.

I put together that example for you in PyNite syntax, its just that one C-G member that is totally wrong, in truth i haven't verified the example but textbooks being wrong tends to be the exception (vs my own code).
```
A = 5
I = 1
E = 300000
G = E / (2*(1+0.3))
J = 1

st = pynite.FEModel3D()
st.AddNode('A',0,0,0)
st.AddNode('B',15,30* sqrt(3) / 2,0)
st.AddNode('C',45,30* sqrt(3) / 2,0)
st.AddNode('D',75,30* sqrt(3) / 2,0)
st.AddNode('E',90,0,0)
st.AddNode('F',60,0,0)
st.AddNode('G',30,0,0)

pairs = set()
Lmin = 30 * sqrt(3) / 2
Lmax = 30.1

for n1 in st.Nodes.values():
    for n2 in st.Nodes.values():

        L = numpy.sqrt((n1.X - n2.X)**2.0 + (n1.Y - n2.Y)**2.0 + (n1.Z - n2.Z)**2.0)

        if L >= Lmin and L <= Lmax and (n1.Name,n2.Name) not in pairs and (n2.Name,n1.Name) not in pairs:
            #print(f'adding {(n1.Name,n2.Name)}')
            pairs.add((n1.Name,n2.Name))

        elif (n1.Name,n2.Name) in pairs or (n2.Name,n1.Name) in pairs:
            pass
            #print(f'skipping {(n1.Name,n2.Name)}, already in pairs')
            
constrained = ('A','E')
for n1,n2 in pairs:
    bkey = f'{n1}_{n2}'
    st.AddMember(bkey,n1,n2,E,G,I,I,J,A)
    

st.DefineSupport('A',True, True, True, False,False,True)
st.DefineSupport('E',False,True,True,False,False,True)

st.AddNodeLoad('F','FY',-1000)
st.AddNodeLoad('G','FY',-2000)
st.Analyze(True)


acpt_values = { ('A','B'):1925,
                ('A','G'):-926,
                ('B','C'):1925,
                ('B','G'):-1925,
                ('C','D'):1541,
                ('F','G'):-1734,
                ('C','F'):382,
                ('C','G'):-382,
                ('C','G'):1541,
                ('D','F'):-1541,
                ('E','F'):-770 }

for member in st.Members.values():
    key = tuple(member.Name.split('_'))
    keyr = tuple(reversed(key))
    
    if key in acpt_values:
        truth = acpt_values[key]
        tested =member.MaxAxial()
        diff =  tested - truth
        pct = abs(diff / truth)
        passes = pct < 0.025
        print(f'test {"-".join(key)} {"pass" if passes else "fail"} {tested}=={truth}?')
        ```

**Comment by JWock82** [comment]
That's correct. By "pinning" the ends of the member you force it to become a two force member, since the only forces it can have at the ends are shear and axial forces. The resultant of those reactions will always be parallel to the member.

The only exception is if you apply a transverse load to the pin-ended member. Then you would get bending stresses, but in reality, that's how a truss member really behaves under its own self weight.

In the example above I still don't see a `DefineReleases` command anywhere.

**Comment by SoundsSerious** [comment]
@JWock82 Ok that makes sense.

So this configuration was the closest I could get the answers to the textbook solution. I tried a few cases with DefineReleases but that threw the answers off very significantly so left it out.

I tried various combinations of the define releases / supports (in z) in this section:
```
constrained = ('A','E')
for n1,n2 in pairs:
    bkey = f'{n1}_{n2}'
    st.AddMember(bkey,n1,n2,E,G,I,I,J,A)
    if n1 not in constrained and n2 not in constrained:
          st.DefineReleases(bkey, Dxi=False, Dyi=False, Dzi=False, Rxi=False, Ryi=True, Rzi=True, Dxj=False, Dyj=False, Dzj=False, Rxj=False, Ryj=True, Rzj=True)
    

st.DefineSupport('A',True, True, True, False,False,True)
st.DefineSupport('E',False,True,True,False,False,True)

for node in st.Nodes.values():
    st.DefineSupport(node.Name,False,False,True,False,False,True)
```
