### ISSUE TITLE
Analysis Optimisations

### ISSUE THREAD

**Issue by bjhowie** [JWock82/PyNite#96]
Hi,

I've been putting PyNite through its paces recently and it seems to be holding up really well, so congrats on creating such a robust FEA solver. I have a few ideas for improvements i'd like to raise for discussion:

1. The Scipy sparse solver doesnt appear to throw an exception when the input stiffness matrix is singular, it simply prints a warning. This isn't ideal for the operation of PyNite, where we want to be able to catch this condition to resolve the instability. I'm not too familiar with Scipy so not sure if there's a way to force it to throw an exception with a singular input matrix, but as a work around maybe PyNite could check the first element in the returned displacement Matrix and if it is 'NaN' then raise the exception manually
2. The solver is very slow for large models with multiple load combinations. The reason for this seems to be that the stiffness matrix is regenerated (and more critically, re-inversed) for each load combination. For linear models (no tension/compression only elements) this seems entirely unnecessry, the stiffness matrix should be able to be generated once, then re-used for every load combination. As an even further optimisation, the stiffness matrix could be pre-inversed then just multiplied with the force matrix for each load combo
3. The above point is not possible for non-linear models however as a thought, potentially the full stiffness matrix could be generated once then just have the stiffness components for the inactive compression/tension only elements subtracted in each iteration/load combo. Unsure what sort of performance increase this would provide as you'd still have to do the matrix inversion in each iteration.

Would be interested to hear your thoughts on the above.

Happy to contribute some code, but I am not particularly familiar with the implementation specifics of the matrix operations I've discussed.

**Comment by JWock82** [comment]
Sorry for the delayed response. I’ve had a lot to take care of on the home front this last 2 weeks.

To answer your questions:

1. I noticed the same thing with the sparse solver. I could manually check if the matrix is singular. PyNite used to do this by checking if the rank of the matrix was less than its smallest dimension. But when I ran the profiler I found it greatly slowed down computation. Catching an exception when the matrix operation failed was much faster. I’m not sure how best to handle this issue without a hefty performance price tag.

2. I set up PyNite this way intentionally so that it would have the ability to do nonlinear analysis (tension/compression and/or P-Delta). I could add another solver option that uses the principle of superposition for users who want the speed boost on linear models. That wouldn’t be too difficult.

3.  Subtracting single element stiffness would be faster than reforming the entire stiffness matrix on each iteration. I’ll have to look into that when I get some time. Right now I’m trying to build out some of the plate meshing features, so this will sit on the back burner for a while.

**Comment by bjhowie** [comment]
As for me, life's been a bit hectic recently...

1. I agree that performing the singularity check adds unnecessary overhead, doesn't surprise me that it had such a performance impact. I think the best method, would just be to check the returned matrix to see if the first element is 'NaN'. I dont believe there's any other occasion where a NaN result would be expected in the node dispalcement matrix? It would be a sure sign that the solve had failed. Not pretty, but i think it would be effective.

2. I think the vast majority of use cases would not require non-linear analysis, so defaulting to non-linear like that results in a huge performance penalty with no benefit to the majority of users. You could add a purely linear solver as you've suggested, or otherwise check if there are any tension/compression only elements in the model before performing the analysis, then perform either a non-linear or linear analysis as appropriate.

3. No problem, just wanted to throw the idea out there

**Comment by JWock82** [comment]
1. I have to look into the 'NaN' thing. If that's what the sparse matrix produces for an unstable structure it should be pretty easy.
2. I tend to disagree. First order (linear) analysis should not be the norm. Building codes for all materials require second order analysis of some sort. Traditionally this has been accomplished on the design side by amplifying loads from a first order analysis using moment magnifiers to account for second order effects. In the US, the 9th Edition steel code contained moment amplification factors in the combined loading check that are a good example of that. However, those design provisions had a hard time keeping up with the design "efficiency" that modern computers create. The 15th Edition steel code has dropped the moment magnification factors in the design equations, and instead requires a "rigorous" second order analysis. The Aluminum Design Manual has followed suit. ACI 318 still permits moment magnification, but has procedures for second order analysis as well. Unless the user is magnifying their own forces during post-processing using extremely restrictive code-regulated procedures. Even P-Delta analysis is not sufficient by itself. In my experience, unfortunately, these code requirements are not well understood by most engineers. Eventually I'd like PyNite to do the Direct Analysis Method.

**Comment by JWock82** [comment]
I just ran the unstable structure test. I didn't see any 'NaN' values in the resulting displacement matrix. I did notice the displacement values in the matrix were extremely large though.

**Comment by bjhowie** [comment]
Did Scipy print the singular Matrix message? I have noticed in the past that an unstable structure doesnt always give a singular matrix. I suspect it's due to a floating point error where the determinant of the matrix isn't exactly zero, but a very small value. Then when the matrix is divided through by the determinant the values blow up.

I think the only way around this would be to check if the determinant is less than some very small value, but as you've said, it's a pretty big performance hit.

**Comment by JWock82** [comment]
No singular matrix message.

**Comment by JWock82** [comment]
Reading through Gallagher's book this morning, I've discovered a simple way to do this. If I work diagonally down the stiffness matrix, any zero terms on the diagonal represent instabilities for the associated degree of freedom. This should be a simple check to implement right after the stiffness matrix is assembled. I'll have a look at doing this soon.

**Comment by JWock82** [comment]
v0.0.66 adds a linear solver. Checking for global stability is also an option you can select now. Leave it turned off to save time.
