### ISSUE TITLE
Refactor oversight

### ISSUE THREAD

**Issue by fdav10** [JWock82/PyNite#98]
Hi there,

Many thanks for the solid FEA library.  I noticed one line that your PEP-8 refactor missed. See below.

https://github.com/JWock82/PyNite/blob/ffc6f12b47ca89b1b13e20e9a0f18a4a63e30e11/PyNite/Member3D.py#L757

**Comment by JWock82** [comment]
Fixed in v0.0.47. Thanks for reporting the bug.
